### ISSUE TITLE
Sentence Embeddings

### ISSUE THREAD

**Issue by nivibilla** [NVIDIA/NeMo-Guardrails#1]
First of all, amazing stuff here. And it's open source?? Icing on the cake.

Forgive me if it's a stupid question, as I haven't fully read the repo yet. But in theory, is it possible to replace the KNN with a sentence embeddings based search? 

I feel like this would be better at understanding the guardrails and put less emphasis on the requirements of high quality of the examples given

Thanks!

**Comment by cparisien** [comment]
Thanks for your interest and your kind words! We're very excited to bring this out to the community and we are looking forward to working with so many great people.

The KNN is currently a sentence embedding search. It uses SentenceTransformers to create embeddings and populates an Annoy index. We're looking at other options as well.

**Comment by nivibilla** [comment]
Ah great. Thanks!
