### ISSUE TITLE
Launching NeMo Guardrails CLI/GUI using a Python Script

### ISSUE THREAD

**Issue by Rishab9991** [NVIDIA/NeMo-Guardrails#103]
I wanted to know if there is a provision to launch the NeMo Guardrails CLI/GUI from Python. If it is possible, please let me know how to do it. Thanks for your support

**Comment by drazvan** [comment]
Hi @Rishab9991!

I'm not sure what you mean. I assume that when you say "GUI", you refer to the server setup. If you want to start it "from Python", this is the relevant line: https://github.com/NVIDIA/NeMo-Guardrails/blob/main/nemoguardrails/cli/__init__.py#L96. 

The CLI as a whole is a Typer app. You can invoke it "from Python" like this: https://github.com/NVIDIA/NeMo-Guardrails/blob/main/nemoguardrails/__main__.py#L24. 

If this does not answer your question, do provide more details on what you're trying to achieve.

**Comment by Rishab9991** [comment]
Thanks for providing the information
