### ISSUE TITLE
Code Correction/Correction feature in NeMo Guardrails

### ISSUE THREAD

**Issue by Rishab9991** [NVIDIA/NeMo-Guardrails#110]
Hi,
Is there a provision in NeMo Guardrails using which we can rectify the raw LLM response and display the rectified LLM response? 
For example, if we ask the LLM to generate a piece of code, can we check for bugs in the code and display the rectified code as the final response? Thanks for your support

**Comment by drazvan** [comment]
Hi @Rishab9991 !

You should be able to follow the same model from the [moderation rail example](https://github.com/NVIDIA/NeMo-Guardrails/tree/main/examples/moderation_rail). A flow along these lines:

```
define flow correct code
  bot ...
  $initial_code = $last_bot_message
  $corrected_code = execute check_code(code=$initial_code)
  if $corrected_code != $initial_code:
    bot remove last message
    bot $corrected_code
```

And you register a custom action `check_code` which does the correction. The `check_code` action can potentially use the LLM again to achieve that.
