### ISSUE TITLE
Flow Problem

### ISSUE THREAD

**Issue by Paddy-90** [NVIDIA/NeMo-Guardrails#113]
Hi,
I use nemoguardrails==0.5.0 and I´ve got a problem with the flows.
Every time I use something like "when" statements I can't use actions anymore. They will be skipped.
Here is a code example:
```
define subflow smart knowledge
  bot ask if knows smart
  when user agree
    bot express readiness
  else when user disagree
    bot explain smart
    bot express readiness
```
The bot express readiness will be skipped and also all action after that will be skipped. 
I tried different ways to use when but nothing really worked. Or is it a problem when flows are to long?

**Comment by florence26** [comment]
I think it is the "if" statement that is not working

**Comment by Siddhijain16** [comment]
Hi,
Any suggestion for this, I am also experiencing the same.
