### ISSUE TITLE
Registering custom embedding search provider while using RailsConfig.from_content function

### ISSUE THREAD

**Issue by prarshah1** [NVIDIA/NeMo-Guardrails#114]
Hello, I am using following logic:
```
rails_config: RailsConfig = RailsConfig.from_content(colang_content=rails_colang_config, yaml_content=rails_yaml_config)
```
Here, I have used custom embedding search provider.
It works when using `RailsConfig.from_path("config")` using `register_embedding_search_provider` , but fails using above code.
Giving following error: 
`
Exception: Unknown embedding search provider: .<custom_provider_name>
`

**Comment by prarshah1** [comment]
After some debugging, noticed there is the following check in the LLMRails's init function:
`
if self.config.config_path
`
So it worked with the following workaround:
`
rails_config: RailsConfig = RailsConfig.from_content(colang_content=rails_colang_config, yaml_content=rails_yaml_config)
rails_config.config_path =<path_to_config_folder>
rails = LLMRails(rails_config)
`

**Comment by austinmw** [comment]
Hi, I ran into the same error, but adding a `rails_config.config_path` didn't fix it for me.

**Comment by drazvan** [comment]
The `RailsConfig.from_content` is meant mainly for quick testing. If a configuration needs custom initialization it's better to take the "put config in a folder" approach. That being said, there should always be a way to achieve the same result using `from_content`. You would typically need to do everything you did in `config.py`, before you create the `LLMRails` instance. If you can provide more details, maybe I can spot where the error is.

**Comment by prarshah1** [comment]
We are packaging the model to deploy it on a different instance, which makes it difficult to pass config from the path.
