### ISSUE TITLE
Bug: Incorrect langchain wrapper when using chat models

### ISSUE THREAD

**Issue by dentro-innovation** [NVIDIA/NeMo-Guardrails#120]
## Current state:
When using a chat model such as `gpt-3.5-turbo` or `gpt-4`, this warning is displayed when initializing LLMRails:

```
.venv/lib/python3.10/site-packages/langchain/llms/openai.py:801: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
```

And this warning / error is shown when generating a bot message:
```
Parameter temperature does not exist for OpenAIChat
```

## Expected behavior:
No warnings are shown and the correct langchain chat model wrapper is used.

## Fix:
This is because in `nemoguardrails/llm/providers.py` is this function:
```
def get_llm_provider(model_config: Model) -> Type[BaseLanguageModel]:
    if model_config.engine not in _providers:
        raise RuntimeError(f"Could not find LLM provider '{model_config.engine}'")

    # For OpenAI, we use a different provider depending on whether it's a chat model or not
    if model_config.model == "openai" and (
        "gpt-3.5" in model_config.model or "gpt-4" in model_config.model
    ):
        return ChatOpenAI
    else:
        return _providers[model_config.engine]
```

The problematic line is this:
```
if model_config.model == "openai" and (
        "gpt-3.5" in model_config.model or "gpt-4" in model_config.model
):
```

This line should be changed from `model_config.model == "openai"` to `model_config.engine == "openai"`:
```
if model_config.engine == "openai" and (
        "gpt-3.5" in model_config.model or "gpt-4" in model_config.model
):
```

Sorry for opening an issue instead of an PR, I was too lazy to set up a GPG key for a commit that changes a single word.

**Comment by drazvan** [comment]
Closed by https://github.com/NVIDIA/NeMo-Guardrails/pull/121.
