### ISSUE TITLE
Can long flows be recognized now? 

### ISSUE THREAD

**Issue by vegetax** [NVIDIA/NeMo-Guardrails#13]
Can long flows be recognized now? I have noticed that when the flow is Q->A->Q->A->Q->A->Bey, it always gets stuck in a QA loop and never triggers the Bey intent.

**Comment by cparisien** [comment]
Thanks for raising this @vegetax. We're taking a close look and will update back shortly.

**Comment by drazvan** [comment]
Hi @vegetax. Yes, long flows should work as well. There was a bug however, which is now fixed. Apologies for the slight delay. Do check and let us know if works for you now.

**Comment by drazvan** [comment]
Closing this. Feel free to re-open if it's still an issue.
