### ISSUE TITLE
HTTP(S)_PROXY not respected?

### ISSUE THREAD

**Issue by ChristianWeyer** [NVIDIA/NeMo-Guardrails#134]
Hello,

when using `requests`-based Pyhton code, I am successfully talking to the LLM endpoints via an HTTP(S) proxy by setting these envs:
```
REQUESTS_CA_BUNDLE=/Users/foo/mycert.pem
HTTPS_PROXY=http://localhost:8081
HTTP_PROXY=http://localhost:8081
```

However, when using the `nemoguardrails` CLI it does not pick up the proxy server config.

Can anybody confirm this?
Thank you.

**Comment by ChristianWeyer** [comment]
Hey @drazvan - ah, it seems I explained it in a wrong way ;-).

Guardrails uses `Request` to make calls to an LLM (like GPt-4). I need to trace the HTTPS calls with an HTTPS proxy on my machine. This works perfectly with other libs (like LlamaIndex, Langchain etc.).

When I use the Guardrail CLI I am not able to get it to respect the proxy server config.

**Comment by drazvan** [comment]
This sounds very weird. Can you do a quick sanity check and print the env variables from python somewhere. As close as possible to the requests call (you can take a quick and dirty approach and edit the code from where it is installed).

**Comment by ChristianWeyer** [comment]
Seems you are not using `requests`, but `aiohttp` :-)
E.g.:
https://github.com/NVIDIA/NeMo-Guardrails/blob/5f2541edb3e1115d48fc219e6e4d287d2d759ca1/nemoguardrails/flows/runtime.py#L393

And `aoihttp` won’t read environment variables by default:
https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=proxy#proxy-support

**Comment by drazvan** [comment]
Correct. Now I realise I misread your initial comment. I thought it works in server mode, but not CLI. But you actually meant "when using `requests`-based Pyhton code".

I guess we can add an `allow_proxy` option in the `config.yml` and when that is set, we pass `trust_env=True` to the constructor in the right places. If you have time to contribute a PR for this, that would hugely appreciated.

**Comment by ChristianWeyer** [comment]
I can try. However, I did not yet get it working by changing the local code (as per your 'dirty approach' mentioned above).
