### ISSUE TITLE
Guardrails is not supported with Marvin 🙋🏻 please integrate

### ISSUE THREAD

**Issue by thanseefpp** [NVIDIA/NeMo-Guardrails#135]
When I was trying to connect the guard with Marvin AIApplication it raised some issues that Marvin is :

# Issue
<img width="1233" alt="Screenshot 2023-09-30 at 4 07 34 PM" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/62167887/1641b9e1-da6e-4d79-bff1-0a27aa427e84">

I have configured some basic rails which are working fine with Langchain -> AzureChatOpenAI and Openai as well. I know you don't build support for Marvin right now. but if it's possible to make it support Marvin that will be an easy solution to integrate these guardrails with Marvin.

### Model Config
<img width="405" alt="Screenshot 2023-09-30 at 4 13 19 PM" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/62167887/f3d58440-50f7-49b7-ad40-fb8e951c4bf0">

### Basic Rail Config
<img width="763" alt="Screenshot 2023-09-30 at 4 13 45 PM" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/62167887/ab42bfbb-ea3d-430b-ba0b-8d89d4186e10">

### Working with AzureChatOpenAI 
<img width="795" alt="Screenshot 2023-09-30 at 4 14 37 PM" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/62167887/1e2a8c53-92ab-4a7f-bca0-d6c54034762e">

### Raising the Above Exception with Marvin
<img width="1265" alt="Screenshot 2023-09-30 at 4 17 19 PM" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/62167887/56dfdaca-2154-40d9-9dfb-aa0a7c5bf833">

### Nemo Guardrails Version which I used.
```
pip install -q nemoguardrails==0.5.0
```

**Comment by drazvan** [comment]
Hi @thanseefpp! The `AIApplication` from marvin is not a subclass of `BaseLanguageModel` from Langchain. You will need to wrap it inside another class that implements that interface. Check out https://github.com/NVIDIA/NeMo-Guardrails/blob/main/docs/user_guide/configuration-guide.md#custom-llm-models and this example: https://github.com/NVIDIA/NeMo-Guardrails/blob/main/examples/llm/hf_pipeline_mosaic/config.py.
