### ISSUE TITLE
How well does this work?

### ISSUE THREAD

**Issue by sradc** [NVIDIA/NeMo-Guardrails#14]
I've looked through the docs in this repo, and the two blog posts, but haven't managed to find an evaluation of how well this works. I'm curious to know if an evaluation has been carried out, and what was found? E.g. how well does this detect jailbreaks? Presumably it doesn't catch all of them, but does it catch common ones? And how well does it map user input to the questions? Presumably sometimes a user might word things strangely, so it doesn't get mapped to the correct thing? Etc. (I'd be interested to know how you would go about benchmarking a system like this.)

**Comment by cparisien** [comment]
Thanks for the comment. We'll be putting out a more fulsome evaluation shortly, breaking down the components like the canonical form generation, flow generation, safety rail accuracy, and so forth. We did a fair bit of adversarial testing with internal groups prior to launch, and you can see (brief) comments about this at the end of the security guidelines doc. With respect to the jailbreaks, we've seen it get pretty good coverage of the current high-ranking prompts on jailbreakchat.com. It doesn't catch all of them, so we'll be looking to improve the approach, and we always appreciate contributions.
