### ISSUE TITLE
How to use quantized meta-llama/Llama-2-7b-chat-hf from huggingface_pipeline  with guardrails 

### ISSUE THREAD

**Issue by Sudhu2004** [NVIDIA/NeMo-Guardrails#155]
I have been trying to use the model with guardrails and there would be an error saying :
`I'm sorry, an internal error has occurred.`

can someone help me solve the problem

**Comment by BlueCestbon** [comment]
me too. How do you solve the problem?

**Comment by Sudhu2004** [comment]
Yeah, I have solved the problem using the similar approach specified below.
 use the same `yaml_content` in the link as required but 
do only small changes in it.

in place of the model dolly use the `quantized Llama2 model` and do the changes accordingly in the `yaml_content` 
link: https://github.com/NVIDIA/NeMo-Guardrails/blob/main/examples/llm/hf_pipeline_dolly/README.md

**Comment by Arrmlet** [comment]
Hello @Sudhu2004 could you share the config.yml file ? The link you attached is not exists anymore.
