### ISSUE TITLE
Runtime Error nemoguardrails 0.1.0

### ISSUE THREAD

**Issue by PetreanuAndi** [NVIDIA/NeMo-Guardrails#16]
Hello guys,

I get this error when trying to do a super simple hello-world example on a Mac: 
`INFO:nemoguardrails.actions.action_dispatcher:Error type object 'Completion' has no attribute 'acreate' while execution generate_user_intent`

Bot response is just:
_I'm sorry, an internal error has occurred._

My config.yaml is the very basic / default : 

<img width="637" alt="Screenshot 2023-05-07 at 19 47 19" src="https://user-images.githubusercontent.com/19908335/236691082-c1c97eb6-f11e-48d5-82b6-97006616b62b.png">

I have some similarly simple .co files
Any idea what the issue could be?

pip list | grep 
langchain               0.0.137
nemoguardrails 0.1.0

**Comment by drazvan** [comment]
Hi @PetreanuAndi!

Can you check the `openai` package version? The `acreate` method was added rather recently (https://github.com/openai/openai-python/issues/98#issuecomment-1338913480). 

I'm using 0.27.5 now.
