### ISSUE TITLE
Phase 3 (Generating bot message) re-generates "Bot intent" and "Bot message" and leaks it into final output

### ISSUE THREAD

**Issue by mukundt** [NVIDIA/NeMo-Guardrails#167]
I'm using Guardrails for multiturn chat. It works well for most uses cases, but I have found one edge case where the behavior is strange.

Here are the last few lines of output logs for Phase 2. Note that the `Bot intent` and `Bot message` are both good.
```
User
i can do it on the app
User intent: pay by themselves
Bot intent: provide assistance for self-payment
Bot message: "That's great! You can make a payment through our mobile app. It's quick and convenient. If you have any questions or need assistance with the process, feel free to ask. Is there anything else I can help you with?"
```

However, things go off the rails during Phase 3. Here are the last few lines of output logs for Phase 3.

```
User
i can do it on the app
Bot
User intent: pay by themselves
Bot intent: thanks user for agreeing to make a payment by provided date
Bot intent: offer send payment link
Bot message: "Would you like me to send you a payment link via text message so you're able to complete the payment at your convenience?"
```

Here is the raw output I get back from the generate function:
```
Bot intent: offer send payment link
Bot message: "Would you like me to send you a payment link via text message so you're able to complete the payment at your convenience?"
```

Not only is the bot response undesirable, but as you can see, the `Bot intent` and `Bot message` strings have leaked into the final bot output. What am I doing wrong? Why is it re-generating the bot intent and bot message during Phase 3, when the correct intent/message have already been generated during Phase 2?

**Comment by drazvan** [comment]
What LLM are you using? From the format of the logs it's a chat model. 

```
User
i can do it on the app
Bot
User intent: pay by themselves
Bot intent: thanks user for agreeing to make a payment by provided date
Bot intent: offer send payment link
Bot message: "Would you like me to send you a payment link via text message so you're able to complete the payment at your convenience?"
```

The last two line in the above block suggests that the LLM decided to predict another bot intent, in addition to the previous one (instead of just the bot message). 
Is this error consistent?

**Comment by mukundt** [comment]
@drazvan I'm using gpt-3.5-turbo. I have noticed similar errors with gpt-4.

This error is consistent with various edge cases like the one I posted. Note that I have set the temperature to 0 for all action types, including generating bot message.

**Comment by mukundt** [comment]
Another case where this error occurs:

```
User
i can pay next week
Bot
User intent: inform about payment date
Bot intent: ask for specific payment date
Bot intent: ask for specific payment date
Bot message: "Thank you for agreeing to make a payment next week. Could you please provide me with the specific date you would like to make the payment?"
```

Raw output:
```
Bot intent: ask for specific payment date
Bot message: "Thank you for agreeing to make a payment next week. Could you please provide me with the specific date you would like to make the payment?"
```

**Comment by mukundt** [comment]
@drazvan just wondering if you have any suggestions on how to make this work with chat models like GPT-4. Thank you, really appreciate it.

**Comment by drazvan** [comment]
It's hard to say why the double intent. It comes down to refining some more the prompt engineering. I'll investigate in more detail soon.
