### ISSUE TITLE
Start off with pre-defined list of messages?

### ISSUE THREAD

**Issue by mukundt** [NVIDIA/NeMo-Guardrails#170]
Guardrails works great when I use it to facilitate my entire conversation, starting from scratch. But when I have a predefined list of messages and want to use Guardrails to _continue_ the conversation, it breaks because it is not able to assign the previous messages to an existing flow. I assume this is because of the `events_history_cache`. Is there a way to prepopulate this cache so that it is able to continue the conversation properly?

My current workaround is to hardcode the pre-defined messages into the `prompts` section in `config.yml`.

**Comment by drazvan** [comment]
@mukundt : can you share more details about the use case? Is the content that you want to pre-populate dynamic? Maybe it should be part of the `sample_conversation` in `config.yml`.

**Comment by mukundt** [comment]
@drazvan basically we have some parts of our conversation that we need to be deterministically conducted, rather than via LLM. But we pipe the whole conversation back into guardrails.

I ended up placing the deterministic portion into `config.yml` as you suggested, and it worked well. Thanks again!
