### ISSUE TITLE
When setting config from path, the model does not listen to off topic guidelines

### ISSUE THREAD

**Issue by birgitbartels** [NVIDIA/NeMo-Guardrails#175]
### Discussed in https://github.com/NVIDIA/NeMo-Guardrails/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **birgitbartels** November  6, 2023</sup>
Hi everyone!

I'm facing some problems with the RailsConfig.from_path(path_name) function. When I enter the path name of my config folder in which you can find my config.yaml file and off_topics.co file, it does seem to work, as the correct predefined greetings are used. However, when I ask a question about one of the off_topic topics, it does not use the predefined answer but generates an answer from chatgpt-3.5-turbo, the model used.

![Screenshot 2023-11-06 at 14 18 38](https://github.com/NVIDIA/NeMo-Guardrails/assets/146433501/d492c1a6-2ecf-43c7-a213-804e3624643c)

When I paste the exact same Colang content as a string into my Python file, on the contrary, and use the function RailsConfig.from_content(colang_content=colang_content, yaml_content=yaml_content) without changing anything else from my code, it does give both the correct predefined greetings and the correct answer when someone asks something about sports/politics. 

![Screenshot 2023-11-06 at 14 17 11](https://github.com/NVIDIA/NeMo-Guardrails/assets/146433501/1c13587d-d3ef-44d8-86ac-0ace1b4dd19f)

Does anyone maybe know why the off-topics do work with RailsConfig.from_content, but not with RailsConfig.from_path or what I might be doing wrong? 

Thank you!!

This is the Colang content I used:

```
# greetings
define user express greeting
    "Hello!"
    "Good afternoon!"

define flow
    user express greeting
    if $name:
        bot express name greeting
    else:
        bot express greeting
    bot offer to help

define bot express greeting
    "Hello, friend!"

define bot express name greeting
    "Hello, $name!"

define bot offer to help
    "How can I help you today?"

# define limits
define user ask politics
    "what are your political beliefs?"
    "thoughts on the president?"
    "left wing"
    "right wing"

define bot answer politics
    "I'm a shopping assistant, I don't like to talk of politics."

define flow politics
    user ask politics
    bot answer politics
    bot offer help
    
define user ask sports
    "what is your favorite football team?"
    "who is Rafael Nadal?"
    "football player"
    "tennis player"
    "match result"
    
define bot answer sports
    "I'm a shopping assistant, I don't know anything about sports."
    
define flow sports
    user ask sports
    bot answer sports
```</div>

**Comment by shashi792** [comment]
I had a similar issue. For me, what worked was the path to the folder. The Absolute path to the dir and not to the file. It picks up all the .co files within the specified path.

**Comment by birgitbartels** [comment]
> I had a similar issue. For me, what worked was the path to the folder. The Absolute path to the dir and not to the file. It picks up all the .co files within the specified path.

I had put the relative path to the folder. I changed it to the absolute path and it indeed seems to work now! Thank you very much!

**Comment by drazvan** [comment]
@birgitbartels ! I'm glad this worked out. I'm closing this.
