### ISSUE TITLE
[Question] input parser?

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/NeMo-Guardrails#176]
Hi, is there any built in capability for input parsers, or should we do custom actions for this functionality?

**Comment by drazvan** [comment]
Hi @austinmw !

In the latest version (which will be published this week,`0.6.0`) and in the `develop` branch, there is now support for "input rails": https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md#input-rails. 

Input rails have the ability call actions and to update the `$user_message` context variable. So, an input parser, would basically need to be implemented in an action and called from an input rail flow. As a quick example: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/sensitive_data_detection/flows.co#L12 the `mask sensitive data on input` flow will look at the input and mask any sensitive data. 

Does this answer your question? If you have a good example for input parsers, we can add this to the examples folder.
