### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by grzywada** [NVIDIA/NeMo-Guardrails#177]
Could the instalation instructions be reviesed and made more robust to changing dependency versions. Currently following instructions leads to instalation of openai 1.0.1 which has a different API structure to version 0.27.5. Maybe having a table listing tested versions for dependencies would be a reasonable idea? Also could the instruction mention any other dependencies that have to be deployed for all of the examples to work?

**Comment by drazvan** [comment]
This is now fixed: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/getting_started/installation-guide.md. 

Thanks @grzywada !
