### ISSUE TITLE
Guardrails incompatible with OpenAI & LangChain

### ISSUE THREAD

**Issue by birgitbartels** [NVIDIA/NeMo-Guardrails#180]
Hello!

I had created a terminal chatbot in which I was testing out my Guardrails configuration and everything worked fine. However, now that OpenAI & LangChain have newer versions, I get a lot of version problems. 

NeMo Guardrails seems to require langchain-0.0251, but many of the other packages I use (langserve, agent-executor, gizmo-agent, langchain-experimental) require langchain>=0.0.322. Moreover, NeMo-guardrails also seems to be incompatible with the newest version of OpenAI, as I now get errors such as "OpenAI does not have an attribute called 'error'".  

Will there be an update of NeMo-Guardrails soon? And if not, what would be the best solution for me so I can work with OpenAI - LangChain & NeMo-Guardrails and further develop my guardrailed RAG-chatbot? Is there a specific combination of versions of the three that does work?

Thanks in advance!

Kind regards.

**Comment by xywen97** [comment]
Same problem

**Comment by trebedea** [comment]
Current release of NeMo Guardrails is compatible with `openai==0.28.1`.
We will be releasing a new version at the end of the month with quite some changes.

**Comment by AlexandraDobrescu** [comment]
@trebedea I am happy to see your comment before `pip installing openai` lib!

**Comment by arun-niranjan-bud** [comment]
> Current release of NeMo Guardrails is compatible with `openai==0.28.1`. We will be releasing a new version at the end of the month with quite some changes.

@trebedea would it be a bad idea to iterate on the main branch, and then tag a new version from that at the end of the month? that would allow the rest of us to test things and provide more useful feedback. It would also mean less divergence between PRs raised by the community and main when it is updated.

as it currently stands, `openai==0.28.1` isn't actually compatible with making calls to OpenAi any more, so I can't test _anything_ in this repository.

**Comment by trebedea** [comment]
@arun-niranjan-bud , just done a fresh install in a new venv using the [installation guide](https://github.com/NVIDIA/NeMo-Guardrails/blob/main/docs/getting_started/installation-guide.md) and `openai==0.28.1` . I don't have any problem running the examples.

**Comment by arun-niranjan-bud** [comment]
thanks @trebedea, I'll try giving it another go and see if I can provide more details as to why it's complaining

**Comment by arun-niranjan-bud** [comment]
ok if I follow the following instructions:
```
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip && pip install wheel
pip install nemoguardrails==0.5.0
pip install openai==0.28.1
```

I then run the following in a main.py using the basic example rails configs

```python
import asyncio
from nemoguardrails import RailsConfig

config = RailsConfig.from_path("./config")

from nemoguardrails import LLMRails

rails = LLMRails(config)

async def get_response() -> str:
    response = await rails.generate_async(messages=[{
        "role": "user",
        "content": "Hello!"
    }])
    return response

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(get_response())
```

which then gives me the following warning:
```
UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
```
and then crashes with the following exception:
```
Error This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions? while execution generate_user_intent
```

**Comment by arun-niranjan-bud** [comment]
Happy to open up a new issue if you prefer, but I think this is a good example of the current incompatibility/stabilty of nemo guardrails with openai/langchain.

Really hope to help get this all working, and thanks for your time 🙏🏾

**Comment by arun-niranjan-bud** [comment]
apologies - I think I pulled the first example config which uses `gpt-3.5-turbo-instruct`, and replacing that with `gpt-3.5-turbo` gets me something operational.

**Comment by trebedea** [comment]
Great! If you want to use `gpt-3.5-turbo-instruct` you can start from the `develop` branch. We will also have a new stable release next week that will upgrade `langchain` version and will contain many more improvements.
