### ISSUE TITLE
Unable to install it on Ubuntu 

### ISSUE THREAD

**Issue by rag9704** [NVIDIA/NeMo-Guardrails#184]
Defaulting to user installation because normal site-packages is not writeable
Collecting annoy==1.0.3
  Downloading annoy-1.0.3.tar.gz (9.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: annoy
  Building wheel for annoy (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/annoy
      copying annoy/__init__.py -> build/lib.linux-x86_64-3.10/annoy
      running build_ext
      building 'annoy.annoylib' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c src/annoylib.cc -o build/temp.linux-x86_64-3.10/src/annoylib.o
      src/annoylib.cc:15:10: fatal error: Python.h: No such file or directory
         15 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for annoy
  Running setup.py clean for annoy
Failed to build annoy
Installing collected packages: annoy
  Running setup.py install for annoy ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for annoy did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/annoy
      copying annoy/__init__.py -> build/lib.linux-x86_64-3.10/annoy
      running build_ext
      building 'annoy.annoylib' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c src/annoylib.cc -o build/temp.linux-x86_64-3.10/src/annoylib.o
      src/annoylib.cc:15:10: fatal error: Python.h: No such file or directory
         15 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> annoy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by rskumar** [comment]
@rag9704 please check if you have python3.10-dev installed.

**Comment by rag9704** [comment]
thanks, it's resolved now!
