### ISSUE TITLE
[Custom Finetuned LLM] - TypeError: cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by AlexandraDobrescu** [NVIDIA/NeMo-Guardrails#188]
Hello, everyone!

 I tried the LLM Wrapper Code with a custom fine-tuned LLM, to use it in my custom rails configs, as my custom engine, but I'm getting the following error `TypeError: cannot pickle '_io.BufferedReader' object`.
I used as a guideline this [Custom LLM Tutorial](https://python.langchain.com/docs/modules/model_io/llms/custom_llm). 

Do you think this is due to the fact that maybe this toolkit does not yet support custom checkpoints?

PS: Thank you very much! ... And I would really like to use further the features of your lib!

**Comment by trebedea** [comment]
Hi @AlexandraDobrescu ,

Can you share your full stack trace? And maybe add a bit of details about your custom fine-tuned model.
We have not encountered this error until now.

Thanks!

**Comment by AlexandraDobrescu** [comment]
Hey, @trebedea ! Thank you so much for your reply.

- Regarding the custom fine-tuned model, this one is a fine-tuned `mistralai/Mistral-7B-Instruct-v0.1` model. I know that on your [main README](https://github.com/NVIDIA/NeMo-Guardrails#supported-llms) page you specify the supported models, and `Mistral` isn't _yet_ over there. Do you know/can disclose if it will be in the future? 
- In the meantime, I solved (_for now_) the `_io.BufferedReader` problem by changing the tokenizer, with a well-known one (`HuggingFaceH4/zephyr-7b-alpha`). The one that I've previously used, was loaded from a `.pkl` file, because it was again (in its essence 😂) a custom tokenizer.
