### ISSUE TITLE
depenency issue conflict chromadb & nemoguardrails 

### ISSUE THREAD

**Issue by shashi792** [NVIDIA/NeMo-Guardrails#193]
There seems to be an version dependency issue between chromadb and nemoguardrail. 
`chromadb 0.4.18 requires typer>=0.9.0, but you have typer 0.7.0 which is incompatible.`
I have tried to rollback both these to older versions i.e. Nemoguardrails  to 0.4.0 and Chromadb to 0.3.27. But no luck. Looks like nemoguardrails uses typer 0.7.0.

**Comment by drazvan** [comment]
@shashi792 : can you upgrade `typer` and check if anything breaks on the NeMo Guardrails side? i.e. test the CLI chat and starting the server. If those works as expected, do submit a PR for the upgrade. Thanks!

**Comment by Pouyanpi** [comment]
This issue is already resolved
