### ISSUE TITLE
Output Moderation Issue: I'm sorry, an internal error has occurred

### ISSUE THREAD

**Issue by shashi792** [NVIDIA/NeMo-Guardrails#204]
I am trying out a simple example on output-moderation. 
`response = rails.generate(messages=[{
    "role": "user", "content": """Replace the letter x with d in the word: 'you are ixiot'."""
}])`

It comes back with an output "I'm sorry, an internal error has occurred." From the log, I also see that the "INFO:nemoguardrails.actions.action_dispatcher:Executing registered action: output_moderation" is invoked.  I'm using  **langchain-0.0.251 nemoguardrails-0.5.0**

Below is the log:

`INFO:nemoguardrails.logging.callbacks:Completion ::   "Here is the modified text: 'you are idiot'. If you need further assistance or have any other requests, feel free to ask."
INFO:nemoguardrails.logging.callbacks:Output Stats :: {'token_usage': <OpenAIObject at 0x7fca67aff380> JSON: {
  "prompt_tokens": 544,
  "completion_tokens": 29,
  "total_tokens": 573
}, 'model_name': 'gpt-3.5-turbo'}
INFO:nemoguardrails.logging.callbacks:--- :: LLM call took 6.84 seconds
INFO:nemoguardrails.actions.llm.generation:--- :: LLM Bot Message Generation call took 6.84 seconds
INFO:nemoguardrails.actions.llm.generation:Generated bot message: Here is the modified text: 'you are idiot'. If you need further assistance or have any other requests, feel free to ask.
INFO:nemoguardrails.flows.runtime:Processing event: {'type': 'StartUtteranceBotAction', 'uid': '06405403-ae94-4438-ab75-a010985314b4', 'event_created_at': '2023-11-30T08:44:36.829010+00:00', 'source_uid': 'NeMoGuardrails', 'script': "Here is the modified text: 'you are idiot'. If you need further assistance or have any other requests, feel free to ask.", 'action_info_modality': 'bot_speech', 'action_info_modality_policy': 'replace', 'action_uid': '3c95170f-df60-4c7b-9679-939c96f3e3de'}
INFO:nemoguardrails.flows.runtime:Event :: StartUtteranceBotAction {'uid': '06405403-ae94-4438-ab75-a010985314b4', 'event_created_at': '2023-11-30T08:44:36.829010+00:00', 'source_uid': 'NeMoGuardrails', 'script': "Here is the modified text: 'you are idiot'. If you need further assistance or have any other requests, feel free to ask.", 'action_info_modality': 'bot_speech', 'action_info_modality_policy': 'replace', 'action_uid': '3c95170f-df60-4c7b-9679-939c96f3e3de'}
INFO:nemoguardrails.flows.runtime:Processing event: {'type': 'StartInternalSystemAction', 'uid': '03159a8b-b44e-4c29-98f0-1b40d441a2f6', 'event_created_at': '2023-11-30T08:44:36.829529+00:00', 'source_uid': 'NeMoGuardrails', 'action_name': 'output_moderation', 'action_params': {}, 'action_result_key': 'allowed', 'action_uid': '0cb98fde-1bce-4e21-b6d9-7f55d9bb9bcc', 'is_system_action': True}
INFO:nemoguardrails.flows.runtime:Event :: StartInternalSystemAction {'uid': '03159a8b-b44e-4c29-98f0-1b40d441a2f6', 'event_created_at': '2023-11-30T08:44:36.829529+00:00', 'source_uid': 'NeMoGuardrails', 'action_name': 'output_moderation', 'action_params': {}, 'action_result_key': 'allowed', 'action_uid': '0cb98fde-1bce-4e21-b6d9-7f55d9bb9bcc', 'is_system_action': True}
INFO:nemoguardrails.flows.runtime:Executing action :: output_moderation
INFO:nemoguardrails.actions.action_dispatcher:Executing registered action: output_moderation
WARNING:nemoguardrails.llm.params:Parameter temperature does not exist for NoneType
ERROR:nemoguardrails.actions.action_dispatcher:Error 'NoneType' object has no attribute 'agenerate_prompt' while execution output_moderation
Traceback (most recent call last):
  File "/Users/abcd/anaconda3/envs/sandbox/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 136, in execute_action
    result = await fn(**params)
  File "/Users/abcd/anaconda3/envs/sandbox/lib/python3.10/site-packages/nemoguardrails/actions/../actions/output_moderation.py", line 48, in output_moderation
    check = await llm_call(llm, prompt)
  File "/Users/abcd/anaconda3/envs/sandbox/lib/python3.10/site-packages/nemoguardrails/actions/llm/utils.py", line 31, in llm_call
    result = await llm.agenerate_prompt(
AttributeError: 'NoneType' object has no attribute 'agenerate_prompt'
INFO:nemoguardrails.flows.runtime:Processing event: {'type': 'hide_prev_turn'}
INFO:nemoguardrails.flows.runtime:Event :: hide_prev_turn {}
INFO:nemoguardrails.rails.llm.llmrails:--- :: Total processing took 38.55 seconds.
INFO:nemoguardrails.rails.llm.llmrails:--- :: Stats: 3 total calls, 38.49818563461304 total time, 1604 total tokens, 1267 total prompt tokens, 337 total completion tokens`

**Comment by dangvansam** [comment]
use `text-davinci-003` instead of `gpt-3.5-turbo`

**Comment by drazvan** [comment]
@shashi792, can you test again using `0.6.0` and also make sure that a main LLM model is set? See #223 .
