### ISSUE TITLE
Allow new line characters inside predefined bot messages

### ISSUE THREAD

**Issue by drazvan** [NVIDIA/NeMo-Guardrails#216]
If "\n" is used inside a predefined bot message, it will be returned as is as part of the message. It should be translated to an actual `\n` character.

**Comment by madangopal16072000** [comment]
I am interested in contributing to this issue. Since I am new to this project can you please point to necessary files.

**Comment by drazvan** [comment]
Thanks @madangopal16072000 !

One way to go about this is to check the content of the `bot_utterance` [here](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/actions/llm/generation.py#L675) and replace all "\n" with the actual `\n` character. 

Make sure you also add a simple test for this. 

Thanks!

**Comment by drazvan** [comment]
@madangopal16072000 : are you still interested in contributing this?
