### ISSUE TITLE
How to get debug output on a Lambda function?

### ISSUE THREAD

**Issue by donatoaz** [NVIDIA/NeMo-Guardrails#217]
I have an AWS Lambda function using Guardrails and on my handler file I do already run

```
logging.basicConfig(level=logging.DEBUG)
```

However I am not getting log messages beyond WARNING and ERROR.

I am trying to troubleshoot an error that I assume is being caused by matching a flow with an action and giving `literal_eval` a json string:

```
[ERROR]	2023-12-12T21:26:35.477Z	7d7830e1-be0a-4ae5-9997-f23d8b3520d7	Error malformed node or string on line 1: <ast.Call object at 0x7f78553181c0> while execution generate_value

Traceback (most recent call last):
File "/var/lang/lib/python3.11/site-packages/nemoguardrails/actions/action_dispatcher.py", line 136, in execute_action
result = await fn(**params)
^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/site-packages/nemoguardrails/actions/llm/generation.py", line 613, in generate_value
return literal_eval(value)
^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/ast.py", line 110, in literal_eval
return _convert(node_or_string)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/ast.py", line 109, in _convert
return _convert_signed_num(node)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/ast.py", line 83, in _convert_signed_num
return _convert_num(node)
^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/ast.py", line 74, in _convert_num
_raise_malformed_node(node)
File "/var/lang/lib/python3.11/ast.py", line 71, in _raise_malformed_node
raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Call object at 0x7f78553181c0>[INFO]	2023-12-12T21:26:35.481Z	7d7830e1-be0a-4ae5-9997-f23d8b3520d7	NeMo Guardrails returned {'role': 'assistant', 'content': "I'm sorry, an internal error has occurred."}
```

Any suggestions on how I can get more detailed debug output when running on lambda?

**Comment by drazvan** [comment]
Hi @donatoaz !
Can you try calling `set_verbose(True)` directly in your code. Like here: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/cli/__init__.py#L63 ?

**Comment by drazvan** [comment]
> Hi @donatoaz ! Can you try calling `set_verbose(True)` directly in your code. Like here: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/cli/__init__.py#L63 ?

Did this help?

**Comment by Karthikreddyk99** [comment]
yep, I too have the same issue, Not working on Lambda

**Comment by drazvan** [comment]
@Karthikreddyk99 : can you share more details? Did you set the verbose mode to `True` as suggested above?

**Comment by Karthikreddyk99** [comment]
Hi @drazvan I opened a new issue where I clearly mentioned the issue and my code. Your help would be great. Thank you.
[link here](https://github.com/NVIDIA/NeMo-Guardrails/issues/608#issue-2392598029)
