### ISSUE TITLE
version on pypi is still 0.5.0

### ISSUE THREAD

**Issue by lawwu** [NVIDIA/NeMo-Guardrails#218]
The version of `nemoguardrails` as of 2023-12-12 is still 0.5.0. I had to install the package from Github to get 0.6.0

https://pypi.org/project/nemoguardrails/

**Comment by drazvan** [comment]
Should be fixed now. The `0.6.0` version is now officially released. 
https://github.com/NVIDIA/NeMo-Guardrails/releases/tag/v0.6.0
