### ISSUE TITLE
Can nemo be used with LLama Guard?

### ISSUE THREAD

**Issue by jackkwok** [NVIDIA/NeMo-Guardrails#226]
LlamaGuard 7b is a new model designed for checking input/output of chat interactions.

https://huggingface.co/meta-llama/LlamaGuard-7b

Assuming I have the model hosted somewhere, what does it take to integrate Nemo with this model?

**Comment by drazvan** [comment]
Hi @jackkwok! Yes, NeMo Guardrails can be used with LlamaGuard. We'll provide an example in the next week or so.

**Comment by shashi792** [comment]
Do we have an example for it already ?

**Comment by drazvan** [comment]
Just a few more days and we'll push the support for Llama Guard into the repo.

**Comment by drazvan** [comment]
Merged: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/guardrails-library.md#llama-guard-based-content-moderation. 

https://github.com/NVIDIA/NeMo-Guardrails/pull/254
