### ISSUE TITLE
Understanding integration with langchain and `RailsRunnable`

### ISSUE THREAD

**Issue by manikyabard** [NVIDIA/NeMo-Guardrails#229]
I wanted to better understand what the `RailsRunnable` object would be and how's the API going to be designed. I see according to `https://github.com/NVIDIA/NeMo-Guardrails/blob/v0.6.0/docs/user_guides/integration-with-langchain.md`, current methods are going to be depreciated in version 0.7.0. Thanks!

**Comment by drazvan** [comment]
Hi @manikyabard! We'll push an initial version tomorrow.

**Comment by drazvan** [comment]
@manikyabard: the PR for the updated interface is available here: https://github.com/NVIDIA/NeMo-Guardrails/pull/235.
