### ISSUE TITLE
Is there a way to access chat history?

### ISSUE THREAD

**Issue by Abubakarjutt** [NVIDIA/NeMo-Guardrails#231]
I am using the following command to interact with the chat application.
```python
messages = [{"role": "user", "content": "hello"}]
res = await rails.generate_async(messages=messages)
print(res)
```

Is there a way to get chat history so I can extract user info from the chat history to varify users? Also can this be done through a single colang file? Can the same colang file contains the chat flows and also the instructions to extract certain information from the user inputs?

**Comment by drazvan** [comment]
Hi @Abubakarjutt ! The chat history is the set of initial messages that you are passing to the `generate` method plus the additional one that is returned.

Related to your second question, do you mean something along these lines: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/advanced/extract-user-provided-values.md ?
