### ISSUE TITLE
Any updates regarding state?

### ISSUE THREAD

**Issue by baravit** [NVIDIA/NeMo-Guardrails#232]
Hi guys, hope you are all well.
Excited about the new release and already testing the new features, thank you for that.

We've discussed in the past about integrating a state object into nemo.
Wanted to check if there is any updates on that one..

Thanks in advanced,
Bar.

**Comment by drazvan** [comment]
Thanks @baravit ! Unless someone from the community can help to contribute, that feature will likely be part of the March release (`0.9.0`).

**Comment by baravit** [comment]
Hi @drazvan, we would love to help.
Where can we get some information about the missing parts / the designed solution?

**Comment by drazvan** [comment]
Let me try to get something to you in the next few days.

**Comment by baravit** [comment]
Hi @drazvan, any updates here:)?

**Comment by drazvan** [comment]
Quick update: the plan is to add a flag in the "generation options" (#256) object to enable returning the state as well. I'll update here in the next couple of days with the final design.
