### ISSUE TITLE
check_facts action question

### ISSUE THREAD

**Issue by shima-khoshraftar** [NVIDIA/NeMo-Guardrails#237]
Hi @drazvan,

I am using check_facts action from the repo on top of my RAG use case. Although the answer returned by the llm is correct, the check_facts action says that the response does not entail the evidence. I am using engine="text-davinci-003" from openAI. I really appreciate your answer. Please let me know if further info is needed.

**Comment by prasoonvarshney** [comment]
Hi @shima-khoshraftar, can you share an example of the retrieved evidence (relevant chunks) and the bot response for which the check is failing if possible?

In general, you first want to make sure that the retrieved chunks are getting passed accurately.

Second, even with reasonable returned chunks, models can make mistakes. We've found the AlignScore technique to fact-checking perform better than methods that prompt LLMs. You can find our evaluation accuracy numbers [here](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/evaluation/README.md#evaluation-results-1) and a guide on how to set up AlignScore-based fact-checking [here](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/guardrails-library.md#alignscore-based-fact-checking)

Finally, even if you'd like to continue using the `self check facts` method instead of `alignscore check facts`, I'd recommend moving away from `text-davinci-003` to `gpt-3.5-turbo-instruct` because the former model is being discontinued by OpenAI in January.

**Comment by trebedea** [comment]
In addition to @prasoonvarshney's answer, any fact-checking method also has false negatives (answers that are correctly entailed by the retrieved chunks / evidence, but the method fails to detect this). If you want to have a lower false negative rate, you should look at models [in this table](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/evaluation/README.md#evaluation-results-1) that have a high positive entailment accuracy. 

In case you are seeing very bad performance compared to the results in the table, maybe you can share some examples.

**Comment by shima-khoshraftar** [comment]
Thanks all for your responses.

Just an update that I am using azure openAI, gpt-35-turbo as the llm now. I saw in the link provided that gpt-35-turbo-instruct has better positive entailment accuracy but I do not have access to that.

Here is my self_check_fact action from repo with small modification on providing the evidence to the function:

async def self_check_facts(evidence_list:list,   
    llm_task_manager: LLMTaskManager,
    context: Optional[dict] = None,
    llm: Optional[BaseLLM] = None,
):
    """Checks the facts for the bot response by appropriately prompting the base llm."""
    #evidence = context.get("relevant_chunks", [])#returned empty
    evidence = evidence_list 
    response = context.get("bot_message")#working now

    print('evidence:', evidence)
    print('response:', response)

    if not evidence:
        # If there is no evidence, we always return true
        return True

    prompt = llm_task_manager.render_task_prompt(
        task=Task.SELF_CHECK_FACTS,
        context={
            "evidence": evidence,
            "response": response,
        },
    )

    # Initialize the LLMCallInfo object
    llm_call_info_var.set(LLMCallInfo(task=Task.SELF_CHECK_FACTS.value))

    with llm_params(llm, temperature=0.0):
        entails = await llm_call(llm, prompt)

    entails = entails.lower().strip()

    # Return 1.0 if LLM response is "yes", otherwise 0.0.
    result = float("yes" in entails)

    print('result:', result)
    return result


how I use it in my rails:
define flow llama
    user ask llama
    $contexts = execute retrieve(query=$last_user_message)
    $answer = execute rag(query=$last_user_message, contexts=$contexts)
    $llm_output = execute get_llm_output(answer=$answer)
    $prompt = execute get_prompt(answer=$answer)
    bot $llm_output
    $accurate = execute self_check_facts(evidence_list=$contexts)
    if not $accurate:
        bot remove last message
        bot inform answer unknown

The response I get for a sample question is sometime 0 and sometimes 1. I know the answer is correct so I expected 1  given that the same llm is prompted to check the entailment.

Here is an example when the evidence(I have to provide the relevant chunks or the evidence would be empty) and response are provided and the response is correct but the entailment returns 0.

question:when this agreement is made?
> RAG Called
evidence: ['Exhibit 10.1\n\n\n                                                           SUBLEASE AGREEMENT\n\n\n        THIS SUBLEASE AGREEMENT (the "Sublease") is made as of this 8th day of February, 2021,.....]
response: This agreement is made on the 8th day of February, 2021.
result: 0.0
{'role': 'assistant', 'content': "I don't know the answer that."}

and in another run the answer to the same questions is:
result: 1.0
{'role': 'assistant', 'content': 'This agreement is made as of the 8th day of February, 2021.'}

As the result for this function do not seem to be stable, I will try with AlignScore technique and update you. Thanks.

**Comment by prasoonvarshney** [comment]
@shima-khoshraftar Yes, AlignScore will definitely be more stable (especially if you have tested that the retrieved context from the RAG call contains the answer in both cases).

**Comment by prasoonvarshney** [comment]
@shima-khoshraftar Yes, AlignScore will definitely be more stable (especially if you have tested that the retrieved context from the RAG call contains the answer in both cases).
