### ISSUE TITLE
How to keep context variables updated in conversation history messgaes throughout a conversation

### ISSUE THREAD

**Issue by prasanth-balaraman-engineer** [NVIDIA/NeMo-Guardrails#246]
Hi team!, I am wondering if there is specific recommended procedure to keep the context variables in the conversation history messages updated throughout the conversation as the new variables are extracted.

I am trying to test a rail/flow for booking flights (toy example), so i have added below colang flow. 

```
define user request book flight
    "I want to book a flight"
    "I want to fly from Bucharest to San Francisco"
    "I want a flight to paris"

define bot request origin city
    "Can you please provide from which city you are travelling from?"

define bot request destination city
    "Can you please provide from which city you are travelling to?"

define bot book flight ticket
    "I have booked flight from $origin_city to $destination_city"

define flow flight booking
    user request book flight

    # Extract the origin city from the user's request as a string literal. If not specified, set as `None`.
    $origin_city = ...

    # Extract the destination city from the user's request  as a string literal. If not specified, set as `None`.
    $destination_city = ...

    while not $origin_city:
        bot request origin city
        user provide origin city

        # Extract the origin city from the user's request as a string literal. If not specified, set as `None`.
        $origin_city = ...

    while not $destination_city:
        bot request destination city
        user provide destination city

        # Extract the origin city from the user's request as a string literal. If not specified, set as `None`.
        $destination_city = ...

    if $origin_city and $destination_city:
        bot book flight ticket
```

I am passing below initial `messages` list to `rails.generate(messages=messages)` and keep appending responses from `assistant` and `user` into `messages` list and trying to provide `$origin_city` in follow up messages. 

Is there a recommended way for me to keep the context variables updated in `messages` as variables are extracted for booking flights throughout the conversations, so that Guardrails runtime will not ask for previusly extracted variables?

```python 
messages = [
    {"role": "context", "content": ""},
    {"role": "user", "content": "I would like to book flights to Chennai."},
]
```

Any help in managing state of context variables throughout the conversation is appreciated. 
Also, please feel free to let me know if there are any better ways to deal with this scenario. Thanks!

**Comment by drazvan** [comment]
Hi @prasanth-balaraman-engineer!

If you use the same `LLMRails` instance, which caches intermediate steps transparently, they will be kept automatically. Just appending the messages as you suggested to the `messages` array is enough. You can always also add explicitly a message with the `role` set to `"context"` and the `content` key set to a dict (in your example above it is a string, should be a dict). However, currently, there's no easy way to extract the value for a variable (you would need to manually inspect the array of events generated behind the scenes, and look for the event that updates the variable). However, in the `0.8.0` release, scheduled for end of February, we'll add an easier way to return data from context, together with the bot message. 

I hope this helps.

**Comment by prasanth-balaraman-engineer** [comment]
> Hi @prasanth-balaraman-engineer!
> 
> If you use the same `LLMRails` instance, which caches intermediate steps transparently, they will be kept automatically. Just appending the messages as you suggested to the `messages` array is enough. You can always also add explicitly a message with the `role` set to `"context"` and the `content` key set to a dict (in your example above it is a string, should be a dict). However, currently, there's no easy way to extract the value for a variable (you would need to manually inspect the array of events generated behind the scenes, and look for the event that updates the variable). However, in the `0.8.0` release, scheduled for end of February, we'll add an easier way to return data from context, together with the bot message.
> 
> I hope this helps.

Thanks for clarifying the question. I will wait for `0.8.0` release end of February to get context together with the bot message. If i need to get context variables before the release, as you said i will try to extract it from the array of events generated.
