### ISSUE TITLE
Make Sentences Transformers and torch optional

### ISSUE THREAD

**Issue by szaher** [NVIDIA/NeMo-Guardrails#250]
NeMo Guardrails depends on torch/cuda to generate embeddings when using SentenceTransformers models but in other cases that's not required. Can we move the torch import to the sentence transformer class and make it optional if the user is going to use  OpenAI embeddings models ?

move it from https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/embeddings/basic.py#L19 to https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/embeddings/basic.py#L117 

The main reason is when installing nemo-guardrails the container image gets really big because of torch and cuda however we might not need them.

**Comment by drazvan** [comment]
Yes, we can definitely do that. Can you test if this is the only change that is needed? 
It is on the roadmap to make SentenceTransformers an optional dependency, but might take another couple of months. The changes you suggested, if enough, can be included in the 0.7.0 release at the end of this month.

**Comment by drazvan** [comment]
This is now covered in https://github.com/NVIDIA/NeMo-Guardrails/releases/tag/v0.7.0. If you don't install SentenceTransformers, it will still work. In `0.7.1`, scheduled in a day or so, we'll also add `fastembed` as the default option, which is much more lightweight.
