### ISSUE TITLE
upgrade typer to 0.9.0

### ISSUE THREAD

**Issue by eneadodi** [NVIDIA/NeMo-Guardrails#251]
Hello,
First of all thank you for the amazing library.

I would like to ask if we can upgrade typer to 0.9.0 or above to handle dependency issues with Chromadb.

Thank you!

**Comment by drazvan** [comment]
Hi @eneadodi! If nothing breaks, then yes. We should keep support for 0.7.0 as well i.e. `typer >=0.7.0, <= 0.9.0`. If you have time to test and make a quick PR for this, that would be great.

**Comment by eneadodi** [comment]
Will do!
Ill make some time this weekend.

**Comment by eneadodi** [comment]
Hello @drazvan !

I completed running 'pytest' and also installed the local repo on a personal project and it didn't crash anything.
A couple of test failed for pytest but it seems like it failed due to dependencies. Here is a screenshot:

![image](https://github.com/NVIDIA/NeMo-Guardrails/assets/41304927/cba16a44-01f3-46ec-bb10-8b90869ef7dd)

**Comment by eneadodi** [comment]
I do not seem to have correct access rights to push to remote remote branch:

git push --set-upstream origin typer-upgrade-nemoguardrails

**Comment by drazvan** [comment]
@eneadodi : you should fork the repo, push the change to the forked repo (on the `develop` branch, or on a separate branch) and create a Pull Request to merge into the `develop` branch of the original repo. Write access to the main repo is currently available only to core developers from NVIDIA.

**Comment by drazvan** [comment]
Fixed in https://github.com/NVIDIA/NeMo-Guardrails/releases/tag/v0.7.0.
