### ISSUE TITLE
config.py loaded default_config.yml twice

### ISSUE THREAD

**Issue by ernesttam** [NVIDIA/NeMo-Guardrails#252]
Do we really need to load the same file twice?

line 28: 
# Load the default config values from the file
with open(os.path.join(os.path.dirname(__file__), "default_config.yml")) as _fc:
    _default_config = yaml.safe_load(_fc)

line 289
# Load the default config values from the file
with open(os.path.join(os.path.dirname(__file__), "default_config.yml")) as _fc:
    _default_config = yaml.safe_load(_fc)

**Comment by drazvan** [comment]
Thanks for reporting this @ernesttam! This is most likely a "merging artifact". We'll fix.
