### ISSUE TITLE
Performance issue using local LLMs

### ISSUE THREAD

**Issue by nashugame** [NVIDIA/NeMo-Guardrails#255]
Hi, 
Getting response directly from LLM takes around 2-5 seconds on average, one has to wait for even more than 5-10 mins to get the response while using nemo-guardrails. I am using **HugginfacepipelineCompatible** to pass the LLM model in the code. Often it runs out of memory CUDA error even for smaller models, though I can see GPU and memory not completely utilised via task manager. Any suggestion to improve the performance?

**Comment by drazvan** [comment]
@nashugame, can you provide more details? With such a huge difference (from 2-5 seconds to 5-10 mins) it doesn't sound like a performance issue, but rather a configuration issue.

**Comment by nashugame** [comment]
Please find the snippet of code I am using:


from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from langchain.llms import HuggingFacePipeline
from nemoguardrails import LLMRails, RailsConfig
from nemoguardrails.llm.helpers import get_llm_instance_wrapper
from nemoguardrails.llm.providers import register_llm_provider, HuggingFacePipelineCompatible
from nemoguardrails.embeddings.index import EmbeddingsIndex, IndexItem, EmbeddingModel
from llama_index.llms import LangChainLLM
import asyncio
import os
from pathlib import Path
import socket
import sys
import torch
sys.path.append(str(Path(__file__).resolve().parent.parent))
import torch
 
 
tokenizer = AutoTokenizer.from_pretrained("/models/zephyr-7b-beta", local_files_only=True, padding_side="left")
model = AutoModelForCausalLM.from_pretrained("/models/zephyr-7b-beta", local_files_only=True, torch_dtype=torch.float16, device_map="auto",trust_remote_code=True)
 
 
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_length=4096,
    do_sample=True,
    temperature=0.2,
    top_p=0.95,
    logprobs=None,
    top_k=40,
    repetition_penalty=1.1
)
 
llm = HuggingFacePipelineCompatible(pipeline= pipe)
 
 
import time
st = time.time()
 
HFPipeline = get_llm_instance_wrapper(
    llm_instance=llm, llm_type="hf_pipeline_llama2"
)
 
register_llm_provider("hf_pipeline_llama2", HFPipeline)
res1 = HFPipeline._call(HFPipeline, prompt="what is capital of India?")
 
en = time.time()
print(res1)
print(en - st)
 
yaml_content = """
models:
  - type: main
    engine: hf_pipeline_llama2
 
  - type: embeddings
    engine: SentenceTransformers
    model: /models/multilingual-e5-small
 
instructions:
  - type: general
    content: |
      Below is a conversation between a bot and a user about the recent job reports.
      The bot is factual and concise. If the bot does not know the answer to a
      question, it truthfully says it does not know.
 
sample_conversation: |
  user "Hello there!"
    express greeting
  bot express greeting
    "Hello! How can I assist you today?"
  user "What can you do for me?"
    ask about capabilities
  bot respond about capabilities
    "I am an AI assistant which helps answer questions based on a given knowledge base."
 
# The prompts below are the same as the ones from `nemoguardrails/llm/prompts/vicuna.yml`.
prompts:
  - task: general
    models:
      - hf_pipeline_llama2
    content: |-
      {{ general_instructions }}
 
      {{ history | user_assistant_sequence }}
      Assistant:
 
  # Prompt for detecting the user message canonical form.
  - task: generate_user_intent
    models:
      - hf_pipeline_llama2
    content: |-
      {{ general_instruction }}
 
      Your task is to generate the user intent for the last message in a conversation, given a list of examples.
 
      This is how a conversation between a user and the bot can go:
      {{ sample_conversation | verbose_v1 }}
 
      This is how the user talks, use these examples to generate the user intent:
      {{ examples | verbose_v1 }}
 
      This is the current conversation between the user and the bot:
      {{ sample_conversation | first_turns(2) | verbose_v1 }}
      {{ history | colang | verbose_v1 }}
    output_parser: "verbose_v1"
 
  # Prompt for generating the next steps.
  - task: generate_next_steps
    models:
      - hf_pipeline_llama2
    content: |-
      {{ general_instruction }}
 
      Your task is to generate the bot intent given a conversation and a list of examples.
 
      This is how a conversation between a user and the bot can go:
      {{ sample_conversation | remove_text_messages | verbose_v1 }}
 
      This is how the bot thinks, use these examples to generate the bot intent:
      {{ examples | remove_text_messages | verbose_v1 }}
 
      This is the current conversation between the user and the bot:
      {{ sample_conversation | first_turns(2) | remove_text_messages | verbose_v1 }}
      {{ history | colang | remove_text_messages | verbose_v1 }}
 
    output_parser: "verbose_v1"
 
  # Prompt for generating the bot message from a canonical form.
  - task: generate_bot_message
    models:
      - hf_pipeline_llama2
    content: |-
      {{ general_instruction }}
 
      Your task is to generate the bot message given a conversation and a list of examples.
 
      This is how a conversation between a user and the bot can go:
      {{ sample_conversation | verbose_v1 }}
 
      {% if relevant_chunks %}
      This is some additional context:
      ```markdown
      {{ relevant_chunks }}
      ```
      {% endif %}
 
      This is how the bot talks, use these examples to generate the bot message:
      {{ examples | verbose_v1 }}
 
      This is the current conversation between the user and the bot:
      {{ sample_conversation | first_turns(2) | verbose_v1 }}
      {{ history | colang | verbose_v1 }}
 
    output_parser: "verbose_v1"
 
  # Prompt for generating the value of a context variable.
  - task: generate_value
    models:
      - hf_pipeline_llama2
    content: |-
      {{ general_instruction }}
 
      This is how a conversation between a user and the bot can go:
      {{ sample_conversation | verbose_v1 }}
 
      This is how the bot thinks:
      {{ examples | verbose_v1 }}
 
      This is the current conversation between the user and the bot:
      {{ sample_conversation | first_turns(2) | verbose_v1 }}
      {{ history | colang | verbose_v1 }}
      {{ instructions }}
      ${{ var_name }} =
    output_parser: "verbose_v1"
"""
colang_content = """
# define niceties
define user express greeting
    "hello"
    "hi"
    "what's up?"
 
define flow greeting
    user express greeting
    bot express greeting
    bot ask how are you
 
# define limits
define user ask sports
    "What is your favorite football team?"
    "Who is Rafael Nadal?"
    "Do you know any football player?"
    "Tennis player"
    "Did you see the match last night?"
 
define bot answer sports
    "I'm a shopping assistant, I don't like to talk of sports."
 
define flow sports
    user ask sports
    bot answer sports
    bot offer help
"""
 
## Initialize rails config
config = RailsConfig.from_content(
    yaml_content=yaml_content,
    colang_content=colang_content
)
 
## Create rails
rails = LLMRails(config)
async def nemorun():
  st = time.time()
  res = await rails.generate_async(prompt="Hello, how are you?")
  en = time.time()
  print(res)
  print(en - st)
 
  st = time.time()
  res1 = await rails.generate_async(prompt="What is your favorite football team?")
  en = time.time()
  print(res1)
  print(en - st)
 
asyncio.run(nemorun())

**Comment by drazvan** [comment]
@trebedea / @prasoonvarshney : can have a look at this?

**Comment by nashugame** [comment]
Guys any updates on this @drazvan @trebedea @prasoonvarshney ?

**Comment by prasoonvarshney** [comment]
Hi @nashugame, the error `torch.cuda.OutOfMemoryError: CUDA out of memory.` means that you are trying to load a model that is bigger than what can fit on your GPU.

I'm not sure what GPU you're using but in practice I've seen that 7b models often need close to 40GB of memory, so an Nvidia RTX A6000 GPU would work well. If a larger GPU is unavailable, I'd recommend using an API-based LLM service of your choice.

**Comment by nashugame** [comment]
Hi @prasoonvarshney , I have my LLMs hosted in form of chat-completion apis, can you pls point out to me how can I feed it to the nemi-guardrails.

**Comment by trebedea** [comment]
Hi @nashugame ,

I was able to run your sample code, I assume you are using `HuggingFaceH4/zephyr-7b-beta`.
For me, the model required about 16-18 GB GPU RAM and the latency were like this (but I changed the `max_length=500` as otherwise in some cases the model continued to generate answers, especially for the first question not using Guardrails).

Using an A6000 GPU, the assistant response generation took 4-8 seconds with Guardrails and about 2-3 seconds without. This makes sense as the prompt is longer with Guardrails and in some cases can require more than a single LLM call. 

A sample output is below:
```
Answer: Delhi is the capital city of India.

// GENERATED A LONGER SEQUENCE OF Q&A IN THIS RUN. IN OTHER RUNS IT GENERATED A SINGLE LINE IN ABOUT 2 SECONDS.

I hope these questions help you test your knowledge about India! Let me know if you have any other requests for quizzes or topics.
11.771398305892944

Hi! I'm doing well, thank you for asking. How may I help you today?
How may I help you today? Before we begin, I'd like to ask, how are you doing today?
7.97413444519043

I'm a shopping assistant, I don't like to talk of sports.
But if you need any assistance with finding information about football teams, please let me know.
6.766375303268433
```  

Can you expand a bit about how you host you LLMs in form of chat-completion APIs? 
The simplest thing to do is to write a wrapper for them in LangChain.
