### ISSUE TITLE
High CPU utilisation when running on AWS 

### ISSUE THREAD

**Issue by maneeshv8** [NVIDIA/NeMo-Guardrails#260]
When running it in the AWS (I tried t3.2xlarge (8 Core), and t3.medium (2 Core), I'm getting high CPU utilisation. Just after the app process starts, it goes to >85%. I tried running the basic ABC bot example provided in GitHub and got identical results. 

Can someone help me figure out what's going on? Does Nemo require a GPU core to run smoothly? 

I tried changing the embedding model to OpenAI one, just to be sure, but even that didn't make any difference.

Any idea @drazvan ? 
<img width="748" alt="Screenshot 2024-01-17 at 2 31 33 AM" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/148588096/06b80c4e-cb14-4aa6-950d-8bde16730a99">

**Comment by drazvan** [comment]
@maneeshv8: are you seeing high usage right after the start? if yes, for how long? does it stay like this e.g. for 1m, 2m, 5m? or does it fade away? Alternatively, do you see the high usage when pushing a query through `generate`/`generate_async`? 

Also, can you provide more details on the setup? are you clonning the repo / `pip install`? or using the Dockefile to build an image? 

And to answer your question, no, it does not need a GPU. It should run fine on CPU.

**Comment by maneeshv8** [comment]
@drazvan After a bunch of testing, I figured out the issue. An issue with my application server configuration caused the high CPU usage. Solved it now. Your questions helped me think about the implementation and test some things out. So, thank you for the response.

**Comment by drazvan** [comment]
Thanks for following up on this @maneeshv8. I'm glad you sorted it out.
