### ISSUE TITLE
Could you upload an unminified version of the Chat UI?

### ISSUE THREAD

**Issue by serhatgktp** [NVIDIA/NeMo-Guardrails#264]
The chat UI is configured to work with a NeMo-Guardrails server wrapped around the provided LLM APIs.

It would be very convenient for me if I had access to the non-minified version of the UI code since I'm trying to use a guardrails server in my own project, but I would like to disallow the user from selecting a configuration.

Would the codeowners be willing to publish the code for the UI? Thanks!

**Comment by drazvan** [comment]
@serhatgktp : We're not planning on providing the non minified version at this point. As a work around, you can start a server with only one config, which should be the one that you want the users to use. Would that work?

**Comment by serhatgktp** [comment]
Hey @drazvan, thank you for your response. The reason I would like to have access to the UI is because I'm actually working on building a server that automatically assigns configs (policies) to users based on their "role". I have made a separate admin panel where an "administrator" can manage multiple configs and determine which configs are assigned to each role.

I was originally planning on using the same template to build it from scratch. However, I wanted to ask before getting started since it would save me some time. No worries if you would rather not publish it though!

Lastly, I plan to make my application open-source after building it as I believe there's value in the concept of centralized guardrails management. I'm also happy to discuss whether the code owners are comfortable with me sharing my own UI code.

Thanks!
