### ISSUE TITLE
Ollama support?

### ISSUE THREAD

**Issue by AndreaBrg** [NVIDIA/NeMo-Guardrails#279]
Hi, I was wondering if NeMo supports using Ollama models https://ollama.ai.

I'm evaluating different guardrail frameworks, and Ollama is a straightforward model to set up and build POCs. Can anyone tell me if these models are supported before I start digging into it?

Thanks.

**Comment by drazvan** [comment]
Hi @AndreaBrg!

Since Ollama is supported by LangChain, it works out of the box. I've played with a configuration a few days ago. Using something similar to this should work: 

```yaml
models: 
- type: main
  engine: ollama
  model: ...
```

**Comment by AndreaBrg** [comment]
@drazvan Thanks!

**Comment by LauraFLR** [comment]
Hi, I used your configuration where I specify ollama as engine but somehow I can only use the 'wizard-vicuna-uncensored' model. When I try to call other models such as llama3.1, there is an issue and it says: there has been an internal error.
I would be very thankful if anyone could help me, I am a data science student and I tried everything already.

**Comment by drazvan** [comment]
@LauraFLR : if you enable verbose mode and share the logs, we might be able to understand better what's happening.

**Comment by LauraFLR** [comment]
Great, thank you for your quick reply :). Here is the content of my terminal in verbose mode:
<img width="701" alt="vicunaPic" src="https://github.com/user-attachments/assets/c916fcd9-5746-4f72-83a3-33224404a2b6">
As specified in my code, I want to use the llama3 model for the self input check rail and the wizard-vicuna-uncensored model for main.:
![image](https://github.com/user-attachments/assets/96550b6d-c9cf-4762-9d1b-2cb835416e3e)

Is there a reason why this is happening? I think maybe there is a problem with NeMo detecting the checkinput.co file in the rails folder? Thank you in advance for your help.
