### ISSUE TITLE
Wrong langchain version is installed as dependency

### ISSUE THREAD

**Issue by aks43725** [NVIDIA/NeMo-Guardrails#287]
When `pip install nemoguardrails`, the package **langchain** version 0.0.352 is always installed as a dependency. This result doesn't match the version restriction (`langchain>=0.1.0,<0.2.0`, which should result in the latest **langchain** 0.1.4) written in [`pyproject.toml`](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/pyproject.toml#L42) and causes conflicts for other packages that require **langchain** (e.g., **langchain_experiment** requires `langchain==0.1.4`).

I've tried `pip install nemoguardrails==0.6.1 langchain==0.1.4` with exact versions, but it errors out as follows:
```bash
Looking in indexes: https://pypi.org/simple
Collecting nemoguardrails==0.6.1
  Using cached nemoguardrails-0.6.1-py3-none-any.whl.metadata (2.8 kB)
Collecting langchain==0.1.4
  Using cached langchain-0.1.4-py3-none-any.whl.metadata (13 kB)
Collecting pydantic==1.10.9 (from nemoguardrails==0.6.1)
  Using cached pydantic-1.10.9-cp310-cp310-macosx_10_9_x86_64.whl.metadata (147 kB)
Collecting aiohttp==3.8.5 (from nemoguardrails==0.6.1)
  Using cached aiohttp-3.8.5-cp310-cp310-macosx_10_9_x86_64.whl.metadata (7.7 kB)
INFO: pip is looking at multiple versions of nemoguardrails to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install langchain==0.1.4 and nemoguardrails==0.6.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain==0.1.4
    nemoguardrails 0.6.1 depends on langchain==0.0.352

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Please let me know what I should do or can try to resolve this weird dependency issue.

**Comment by drazvan** [comment]
Hi @aks43725! The code on the `develop` branch is in preparation for `0.7.0`, which will use `langchain>=0.1.0,<0.2.0` . But it is not yet published (will be in the next 24 hours). The `0.6.1` version had a 'langchain' specific version dependency, hence the conflict.

**Comment by aks43725** [comment]
Thanks for pointing it out, @drazvan. Didn't expect to see the `develop` as the default branch but that explains what I got.
