### ISSUE TITLE
Weird result with hello_world.ipynb

### ISSUE THREAD

**Issue by AndreaBrg** [NVIDIA/NeMo-Guardrails#290]
Hi,
I'm trying to experiment with NeMo-Guardrails, especially the [hello_world example](https://github.com/NVIDIA/NeMo-Guardrails/blob/main/docs/getting_started/1_hello_world/hello_world.ipynb), but I'm getting weird results were the bot response contains an entire made-up conversation instead of just the greetings.

This is my `config.yml`:
```
models:
- type: main
  engine: ollama
  model: llama2:13b
  parameters:
    base_url: http://localhost:11434
```

This is the `rails.co`
```
define user express greeting
  "Hello"
  "Hi"
  "Wassup?"

define flow greeting
  user express greeting
  bot express greeting
  bot ask how are you

define bot express greeting
  "Hello World!"

define bot ask how are you
  "How are you doing?"
```

This is the Python script:
```
from nemoguardrails import RailsConfig, LLMRails

if __name__ == '__main__':
    config = RailsConfig.from_path(config_path="./configs")
    rails = LLMRails(config, verbose=True)

    history = [{"role": "user", "content": "Hello!"}]
    bot_message = rails.generate(messages=history)
    info = rails.explain()

    info.print_llm_calls_summary()
```
Here you can find the logs printed when the script is executed [logs.txt](https://github.com/NVIDIA/NeMo-Guardrails/files/14122441/logs.txt); as you can see, the `bot_message` does not follow the guidelines set in `rails.co`.

Can anyone help me understand what I'm doing wrong? Thanks!

**Comment by AndreaBrg** [comment]
I also did a test using actions and enabling logging, it seems like the registered action is not called.

This is the `rails.co`:
```
define flow
    user ...
    execute my_function(my_param=$last_user_message)
```

This is the Python file:
```
import logging
import warnings

from nemoguardrails import RailsConfig, LLMRails

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO)


def my_function(my_param):
    print(f"THIS IS MY FUNCTION WITH PARAMETER {my_param}")


if __name__ == '__main__':
    config = RailsConfig.from_path(config_path="guardrails_configs_function")
    rails = LLMRails(config, verbose=True)

    rails.register_action(my_function, name="my_function")

    history = [{"role": "user", "content": "Hello!"}]
    bot_message = rails.generate(messages=history)
    info = rails.explain()
```

Here are the logs: [logs.txt](https://github.com/NVIDIA/NeMo-Guardrails/files/14114619/logs.txt)

I would appreciate any help.

**Comment by drazvan** [comment]
Hi @AndreaBrg!

From your first message, it seems that the `llama2:13b` model does not follow the pattern for the prompt. This means the prompt needs to be tweaked to a different format (e.g., in the same way we have different prompts for dolly-3b: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/llm/prompts/dolly.yml). This needs experimentation.  

In your second message, I think you need to define at least one canonical form, e.g. `define user express greeting` and then it should work. If there are no canonical forms, then the dialog rails are not used.

I hope this helps.

**Comment by AndreaBrg** [comment]
@drazvan Thanks for the help. Now, the function is correctly called.

**Comment by faisnain** [comment]
Hi @AndreaBrg can you tell me how you were able to solve the first message? 

I am using the same model as you but still the answers are giving me weird results. I did try the same with second type that you posted. Still the greeting is not getting detected and going into the chain.

**Comment by kaushikabhishek87** [comment]
Same issue
