### ISSUE TITLE
Can NeMo be used with TitanML?

### ISSUE THREAD

**Issue by Wildshire** [NVIDIA/NeMo-Guardrails#295]
Hello

I was wondering if NeMo is compatible with TitanML, and if so, I want to ask if there are any tutorials with it.

[TitanML](https://docs.titanml.co/docs/intro)

Thanks in advance

**Comment by drazvan** [comment]
Since there is already a LangChain connector, it should work: https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/llms/titan_takeoff.py. 
Something along the lines:

```yaml
models:
- type: main
  engine: titan_takeoff
  ...
```

I don't know the exact other parameters, but it should work. Let us know if you need help.

**Comment by Wildshire** [comment]
Hi @saradiazdelser 

Thanks a lot for the info! I tried it and it has worked fine.
