### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by JarvisYan0802** [NVIDIA/NeMo-Guardrails#3]
I've run the demo py file. It can return the message I want correctly, but always raises a RuntimeError: "Event loop is closed". How dose it happen and what can I do?

**Comment by drazvan** [comment]
Hi @JarvisYan0802 ! Can you provide more details on this? I am not able to reproduce the error. Did you change anything to the `demo.py` file? If not, can you share more details about the environment (i.e. python version, venv or not, OS)? Thanks!

**Comment by armstrongsam25** [comment]
Happening for me, too. 
[errors.txt](https://github.com/NVIDIA/NeMo-Guardrails/files/11433680/errors.txt)

I was walking through the topical_rails example. It seems to happen randomly. I modified the script slightly by putting the rails.generate() function in a try/except and a while loop. Even though the exception occurred, it still generates output.
[main_file.txt](https://github.com/NVIDIA/NeMo-Guardrails/files/11433695/main_file.txt)

**Comment by drazvan** [comment]
Thanks for reporting this @armstrongsam25! We need to investigate further as I can't reproduce yet. We'll keep you posted. What OS/python version are you using?

**Comment by armstrongsam25** [comment]
OS: Win11 Enterprise, Version 21H2, Build 22000.1880
Python: 3.8.10
