### ISSUE TITLE
pip package installs unexpected module "examples"

### ISSUE THREAD

**Issue by piotrm0** [NVIDIA/NeMo-Guardrails#304]
Hi; I'm unsure whether this is expected but I see that installing the nemo guardrails package installs two additional modules beyond "nemoguardrails": "examples" and "chat-ui". If possible, could those be renamed to something indicative that they are for nemoguardrails or can they be moved to under nemoguardrails module? "examples" is especially problematic as it can cause unexpected import errors when working with unrelated code that contains "examples" as a module.

**Comment by drazvan** [comment]
Hi @piotrm0! Yes, we are aware of this issue. We'll target to fix this for the `0.9.0` release.
