### ISSUE TITLE
passthrough field not properly initiated in RailsConfig

### ISSUE THREAD

**Issue by yuanboww** [NVIDIA/NeMo-Guardrails#305]
Following the demo from [langchain integrations](https://github.com/NVIDIA/NeMo-Guardrails/blob/a7874d15939543d7fbe512165287506f0820a57b/examples/scripts/langchain/experiments.py). however it keeps erroring out with: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[207], line 1
----> 1 guardrails = RunnableRails(config=rails_config, passthrough=True)

File ~/Library/Python/3.9/lib/python/site-packages/nemoguardrails/integrations/langchain/runnable_rails.py:49, in RunnableRails.__init__(self, config, llm, tools, passthrough, runnable, input_key, output_key)
     46 self.passthrough_bot_output_key = output_key
     48 # We override the config passthrough.
---> 49 config.passthrough = passthrough
     51 self.rails = LLMRails(config=config, llm=llm)
     53 if tools:
     54     # When tools are used, we disable the passthrough mode.

File ~/Library/Python/3.9/lib/python/site-packages/pydantic/main.py:357, in pydantic.main.BaseModel.__setattr__()

ValueError: "RailsConfig" object has no field "passthrough"
```

**Comment by drazvan** [comment]
This is weird, as the `passthrough` field is definitely defined (https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/config.py#L451). 

How exactly are you running this?
This could potentially happen if you cloned the repo before, did a `pip install .` (which copies the .py files to the lib folder), and now you've pulled the changes and tried to run. You would be effectively running the examples from the current code base, but with an older installed version. In this case, doing a `pip install .` again, or even better, `pip install -e .` should fix the issue.
