### ISSUE TITLE
Expose the `verbose` parameter through `RunnableRails`.

### ISSUE THREAD

**Issue by drazvan** [NVIDIA/NeMo-Guardrails#312]

**Comment by d-mariano** [comment]
@drazvan I appreciate this, it certainly is a good first issue! I've taken a stab at this, please check out the PR [here](https://github.com/NVIDIA/NeMo-Guardrails/pull/389). I left a question or two around testing.

**Comment by drazvan** [comment]
Thanks @d-mariano ! 
#389
