### ISSUE TITLE
input rails and output rails still not working properly

### ISSUE THREAD

**Issue by shimada-r** [NVIDIA/NeMo-Guardrails#317]
I inquired in this thread.
https://github.com/NVIDIA/NeMo-Guardrails/issues/203

I upgraded to v0.7.1, but it doesn't work properly, so I will check it.
I am testing input rails and output rails, but neither output is as expected. Could you tell me how to respond?

1)input rails
  The output result of print(info.llm_calls [0] .completion) is not only Yes and No, but also the description is output.
<img width="943" alt="input" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/122951282/15f7b9f1-adc3-4b8c-8c36-47b0e39f8e1f">

  This is the same as the result of the above query.
  I think that this event is probably causing the judgment of prompt injection to be abnormal.

2)output rails
 According to the result of info.print_llm_calls_summary(), it was stopped by self check.
<img width="438" alt="output_1" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/122951282/de7fd350-df1f-4ba8-a558-bacf57d8a247">

According to sample below, I should get to at least output check.
 https://github.com/NVIDIA/NeMo-Guardrails/tree/develop/docs/getting_started/5_output_rails

Also, if the input rails are unhealthy or print(info.llm_calls [2] .prompt) fails and print(info.llm_calls [0] .prompt) works fine.
But even then, the output check is not reached.
<img width="467" alt="output_2" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/122951282/fb2807bc-11a9-4c3f-8b7b-dee37cc556b9">

As a result, output rails has never been able to verify the correct output.
Is there any solution?

**Comment by drazvan** [comment]
Thanks for following up @shimada-r. The "stop tokens" fix did not make it to `0.7.0`/`0.7.1`. The PR https://github.com/NVIDIA/NeMo-Guardrails/pull/293 is in review now and should make it to `0.8.0`. Let's retest once that's done. Thanks for your patience!
