### ISSUE TITLE
Langchain router implementation AIMessage issue

### ISSUE THREAD

**Issue by Amiromar1** [NVIDIA/NeMo-Guardrails#318]
Hello

I am trying to implement guardrails at the end of my router chain implemented using langchain. The structure is broadly

input ==> router ==> chooses a path ==> path executes ==> guardrails ==> fail

The actual LCEL implemention of the chain is:

`full_chain = {"router": chain, "question": lambda x: x["question"]} | branch | guardrails`

The failure results in the error message attached below.

<img width="374" alt="image" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/84646355/52833c7e-e58f-40ce-938c-055de46773e7">

**Comment by drazvan** [comment]
Hi @Amiromar1!

Indeed, this is not supported. Let me explain. In your case, you add the guardrails after the LLM has been called. So, I guess you're looking to add some sort of output guardrails. Currently the `RunnableRails` does not support invoking just the output rails. We're just adding support for this in the python API (should be merged to `develop` Mon/Tue). After that, we can look into updating the `RunnableRails` to make use of that feature. 

Meanwhile, to achieve what you want, you can just put the guardrails first:

```python
full_chain = guardrails | ({"router": chain, "question": lambda x: x["question"]} | branch)
```

If you have a config that doesn't have any input/dialog rails, and only output rails, you will get the same behavior. 
```yaml
rails:
  output:
    flows: 
      - self check output
```

Also, if you want to contribute and test the changes after we update the python API, let me know and I can provide more guidance. 

Thanks!

**Comment by Amiromar1** [comment]
Just posting an update for anyone interested.

There is a hacky way to get around this which is to simply use the Bedrock object in Langchain instead of the BedrockChat model; this will output a string which is what guardrails expects and will resolve this error.

Doing this will allow you to run the chain as I have outlined it above.

**Comment by drazvan** [comment]
Thanks for the update @Amiromar1. While this will now longer raise an error, it will not behave exactly as you intend it to. The  string that will be sent to the guardrails will be treated as user input rather than LLM output.
