### ISSUE TITLE
Action 'user_query' not found.

### ISSUE THREAD

**Issue by PascalStrewe** [NVIDIA/NeMo-Guardrails#329]
Hi all, 

I am a bit lost. I ran my code 2 days ago and it worked flawlessly. Now the same code gives the error code:
Action 'user_query' not found. I checked the decorator, it shouldn't be the problem. And as mentioned, it worked before.

My config.yml calls it like this:
...previous code
```
rails:
  input:
    flows:
      - self check input
      - user query

  output:
    flows:
      - self check output
```

and then I have the actions.py file in the same directory that is as follows:

```python
from typing import Optional
from nemoguardrails.actions import action
from llama_index import SimpleDirectoryReader
from llama_index.llama_pack import download_llama_pack
from llama_index.indices.query.base import BaseQueryEngine
from llama_index.response.schema import StreamingResponse

query_engine_cache = None

def init():
    global query_engine_cache
    if query_engine_cache is not None:
        print('Using cached query engine')
        return query_engine_cache
    load data
    documents = SimpleDirectoryReader("data").load_data()
    print(f'Loaded {len(documents)} documents')
    RecursiveRetrieverSmallToBigPack = download_llama_pack(
        "RecursiveRetrieverSmallToBigPack", "./recursive_retriever_stb_pack"
    )
    recursive_retriever_stb_pack = RecursiveRetrieverSmallToBigPack(documents)
    query_engine_cache = recursive_retriever_stb_pack.query_engine
    return query_engine_cache

def get_query_response(query_engine: BaseQueryEngine, query: str) -> str:
    response = query_engine.query(query)
    if isinstance(response, StreamingResponse):
        typed_response = response.get_response()
    else:
        typed_response = response
    response_str = typed_response.response
    if response_str is None:
        return ""
    return response_str

@action(name="user_query", is_system_action=True)
async def user_query(context: Optional[dict] = None):
    user_message = context.get("user_message")
    print('user_message is ', user_message)
    query_engine = init()
    return get_query_response(query_engine, user_message)
```

Files are from:
https://towardsdatascience.com/nemo-guardrails-the-ultimate-open-source-llm-security-toolkit-0a34648713ef

**Comment by drazvan** [comment]
Hi @PascalStrewe!

If there's an error when importing the `actions.py` module, then the action does not get registered. The importing error is rather silent right now, we need to fix that and make it more visible. I suspect this is the case with your `actions.py`. There's a `load data` line, which I think should have been a comment. 

To test quickly that that the file is parsing correctly, and there are no other issues, you can just run it directly `python actions.py` (even though it should do nothing).

**Comment by PascalStrewe** [comment]
Thank you! Yes, now I see that I get an import error in the actions.py file for the SimpleDirectory of llama-index. 
Will investigate that one. 

Have a great weekend!
