### ISSUE TITLE
Creating default flow for any non predefined Intents

### ISSUE THREAD

**Issue by msalhab96** [NVIDIA/NeMo-Guardrails#330]
Hello everyone,

Suppose I have two intents, each with a straightforward response. However, I want to implement a default flow that triggers a specific action if the user's input doesn't match any of these two predefined intents, is there any way to do this other than enforcing that in the prompt to generate a general intent if no intent matched?

Thank you in advance for your help!

**Comment by drazvan** [comment]
You can use a flow like this:
```
define flow 
  user ...
  # do something else
```
