### ISSUE TITLE
Error while using chain with nemoguardrails

### ISSUE THREAD

**Issue by VpkPrasanna** [NVIDIA/NeMo-Guardrails#340]
Error while following the [example](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/langchain/chain-with-guardrails/chain-with-guardrails.ipynb) in the repo 
![Screenshot from 2024-02-19 18-42-59](https://github.com/NVIDIA/NeMo-Guardrails/assets/30804112/b1f47adb-b426-4774-9f09-69a1dc95b934)

**Comment by drazvan** [comment]
@VpkPrasanna : can you double check that the patching has been applied? (it's in the pre-requisites section)
```python
import nest_asyncio

nest_asyncio.apply()
```

**Comment by drazvan** [comment]
Make sure you run through all the cells in the notebook in order.
