### ISSUE TITLE
Add additional LLM Providers 

### ISSUE THREAD

**Issue by VpkPrasanna** [NVIDIA/NeMo-Guardrails#351]
hi Team ,
I noticed presently nemoguard rails support onlu HF pipeline and trition inference server . 
please try to add other llm providers like vllm , ctransformers , ollama and there are many others ?

**Comment by drazvan** [comment]
Hi @VpkPrasanna! It supports any LLM provider that is already included in LangChain (https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md#supported-llm-models). vLLM and Ollama definitely work as we've played with them.

**Comment by VpkPrasanna** [comment]
> Hi @VpkPrasanna! It supports any LLM provider that is already included in LangChain (https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md#supported-llm-models). vLLM and Ollama definitely work as we've played with them.

is it possible to have a detailed docs on the capability of nemo gurad rails along with the customizations ?
it is hard to search and find in markdowns

**Comment by drazvan** [comment]
Yes, we are reworking the documentation, and it will be published on a separate website with better search functionality. This will happen in about a month from now.
