### ISSUE TITLE
Exception: Error evaluating 'generate_value("Extract the user name")': Function 'generate_value' not defined, for expression 'generate_value("Extract the user name")'.

### ISSUE THREAD

**Issue by swethmandava** [NVIDIA/NeMo-Guardrails#36]
How can i add generation actions to my flow? It seems like they're added by default [here](https://github.com/NVIDIA/NeMo-Guardrails/blob/95032c139dcef59705561a67ab9f7e8dfcd60bf6/nemoguardrails/rails/llm/llmrails.py#L84) but when I print the following

```
    app = LLMRails(config)

    print(app.runtime)
```

I only see a few default actions that are defined [here](https://github.com/NVIDIA/NeMo-Guardrails/blob/main/nemoguardrails/actions/actions.py)

**Comment by drazvan** [comment]
Hi @swethmandava! Can you check the exact version you are using? The `generate_value` action was added in 0.2.0.

**Comment by swethmandava** [comment]
I'm on the latest

```
Name: nemoguardrails
Version: 0.2.0
Summary: NeMo Guardrails is an open-source toolkit for easily adding programmable guardrails to LLM-based conversational systems.
Home-page: https://github.com/NVIDIA/NeMo-Guardrails
Author: NVIDIA
Author-email: nemoguardrails@nvidia.com
License: 
Location: /Users/swethamandava/miniconda3/lib/python3.10/site-packages
Requires: aiohttp, annoy, fastapi, httpx, langchain, pydantic, PyYAML, requests, sentence-transformers, setuptools, simpleeval, starlette, typer, typing-extensions, uvicorn
Required-by: 
```

On a side note, with the old formatting I can get this in the logs

`INFO:nemoguardrails.actions.llm.generation:Generated value for $name: "John"
` 
Is it possible to extract this value out of the flow? like output as context to app.generate?

**Comment by grupocopa** [comment]
I am having the same issue, version 0.9.0

**Comment by Pouyanpi** [comment]
Hi @grupocopa , 

can you share your config to reproduce the issue.

Maybe following from the repo addresses your issue

```colang
define flow
  user ask math question

  # Extract the math question from the user's input.
  $math_query = ...

  execute wolfram alpha request(query=$math_query)
  bot respond to math question

# The flow above is equivalent to the one below:
# define flow
#   user ask math question
#   $math_query = execute generate_value(instructions="Extract the math question from the user's input.")
#   execute wolfram alpha request(query=$math_query)
#   bot respond to math question
```

**Comment by grupocopa** [comment]
Hey @Pouyanpi, thank you very much for your explanation!!

It worked, and this is my example:

```
    # Executa a função Python para buscar o orçamento
    $rem = execute generate_value(instructions="Extract the REMEDIO inserted by user, as variable $rem")
    $preco = execute teste_budget(remedio=$rem)
```

This example at "$variable = ..." does not work to me, like I mentioned [on this link](https://github.com/NVIDIA/NeMo-Guardrails/discussions/721#discussioncomment-10530838).

Again: thank you very much for your explanation, it was very clarifying and worked :)
