### ISSUE TITLE
Llama 2 example not working with nemoguardrails

### ISSUE THREAD

**Issue by nairajay2k** [NVIDIA/NeMo-Guardrails#361]
Hi,

This is what I get

(venv) ajay@e2e-72-9:~/NeMo-Guardrails$ nemoguardrails server --config ~/venv/lib/python3.10/site-packages/examples/configs/llm/config_master/ --port 5000 
/home/ajay/venv/lib/python3.10/site-packages/langchain_community/llms/__init__.py:166: LangChainDeprecationWarning: `` was deprecated in LangChain 0.0.22 and will be removed in 0.2. An updated version of the  exists in the langchain-community package and should be used instead. To use it run `pip install -U langchain-community` and import as `from langchain_community.chat_models import ChatDatabricks`.
  warn_deprecated(
/home/ajay/venv/lib/python3.10/site-packages/langchain_community/llms/__init__.py:317: LangChainDeprecationWarning: `` was deprecated in LangChain 0.0.22 and will be removed in 0.2. An updated version of the  exists in the langchain-community package and should be used instead. To use it run `pip install -U langchain-community` and import as `from langchain_community.chat_models import ChatMlflow`.
  warn_deprecated(
INFO:     Started server process [19063]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/home/ajay/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ajay/venv/lib/python3.10/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/home/ajay/venv/lib/python3.10/site-packages/starlette/routing.py", line 711, in startup
    await handler()
  File "/home/ajay/venv/lib/python3.10/site-packages/nemoguardrails/server/api.py", line 319, in startup_event
    config_module.init(app)
  File "/home/ajay/venv/lib/python3.10/site-packages/examples/configs/llm/config_master/config.py", line 128, in init
    config = llm_rails.config
AttributeError: 'FastAPI' object has no attribute 'config'

ERROR:    Application startup failed. Exiting.

Please let me know what to do. I am a newbie.

**Comment by drazvan** [comment]
Hi @nairajay2k!

This is very likely because you were pointing the server to a "single config" folder (instead of a folder with subfolders for multiple configs). Many people have run into the issue so we decided to allow the server to be pointed to a single config. It's just been fixed in https://github.com/NVIDIA/NeMo-Guardrails/pull/362. It will be released in `0.8.0` tomorrow.

**Comment by nairajay2k** [comment]
Hi @drazvan , Its having another issue on 0.8.0 tag.

When I run llama 7b as
nemoguardrails chat --config ~/venv/lib/python3.10/site-packages/examples/configs/llm/hf_pipeline_llama2/
(I changed occurance of 13b to 7b so it fits on my 24GB GPU)
This is what I get
WARNING:nemoguardrails.actions.action_dispatcher:Error while execution generate_user_intent: 'NoneType' object does not support item assignment
I'm sorry, an internal error has occurred.
