### ISSUE TITLE
Hi llama 2 example has another issue on 0.8.0 tag.

### ISSUE THREAD

**Issue by nairajay2k** [NVIDIA/NeMo-Guardrails#366]
Hi @drazvan , Its having another issue on 0.8.0 tag.

When I run llama 7b as
nemoguardrails chat --config ~/venv/lib/python3.10/site-packages/examples/configs/llm/hf_pipeline_llama2/
(I changed occurance of 13b to 7b in the config.yml and config.py so it fits on my 24GB GPU)
This is what I get
WARNING:nemoguardrails.actions.action_dispatcher:Error while execution generate_user_intent: 'NoneType' object does not support item assignment
I'm sorry, an internal error has occurred.

_Originally posted by @nairajay2k in https://github.com/NVIDIA/NeMo-Guardrails/issues/361#issuecomment-1968759370_

**Comment by drazvan** [comment]
@nairajay2k ! The bug should be fixed now. You can also install `nemoguardrails==0.8.0` directly from PyPI.
