### ISSUE TITLE
Pydantic causing installation issues - could it be less specific?

### ISSUE THREAD

**Issue by swethmandava** [NVIDIA/NeMo-Guardrails#37]
#0 105.8 The conflict is caused by:
#0 105.8 vocode 0.1.0 depends on pydantic==1.10.5
#0 105.8 nemoguardrails 0.2.0 depends on pydantic==1.10.6
#0 105.8 vocode 0.1.0 depends on pydantic==1.10.5
#0 105.8 nemoguardrails 0.1.0 depends on pydantic==1.10.6

**Comment by drazvan** [comment]
This is now fixed. Thanks for the suggestion @swethmandava!
