### ISSUE TITLE
Is there quota limitation of openai_api_key in Hello World example?

### ISSUE THREAD

**Issue by Magi2B0y** [NVIDIA/NeMo-Guardrails#371]
I am sure I have balance in my openai account, but it still have this insufficient_quota ERROR when i run the Hello World example.

Error while execution generate_user_intent: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

![1709368043338](https://github.com/NVIDIA/NeMo-Guardrails/assets/71159539/811983c9-1ab1-4007-b6dd-68a1140cd003)
![1709368173921](https://github.com/NVIDIA/NeMo-Guardrails/assets/71159539/bae197ee-1f65-481b-bf76-c062baa610b9)

**Comment by Magi2B0y** [comment]
Resetting Pycharm will be ok.

**Comment by drazvan** [comment]
This is weird. Maybe it was a temporary issue with the API? Is this still reproducible?

**Comment by Magi2B0y** [comment]
I don't know why appeared this ERROR. But when I restart Pycharm, it's disappeared.
Thanks your answer.
