### ISSUE TITLE
Streaming a response from a custom action

### ISSUE THREAD

**Issue by msalhab96** [NVIDIA/NeMo-Guardrails#373]
Hello, 

I have the below custom action and want to stream the output to the user, taking into consideration I'm not using any output rails, is it doable?, if yes, how to do that?

```python
@action(is_system_action=True)
async def call_llm(user_query: str, llm: Optional[BaseLLM]) -> str:
    user_query = add_temp(user_query)
    response = llm.invoke(user_query)
    # Streaming the response here 
```

here's how the flow look like

```
define flow
    user ...
    $user_query = execute my_action()
    execute call_llm(user_query=$user_query)
    stop
```

**Comment by drazvan** [comment]
Hi @msalhab96! This is a good question. I've just created a PR for this: #377.

The important piece is that you need to pass the NeMo Guardrails streaming handler (which you can fetch using `streaming_handler_var.get()`) to the LLM call using the `config.callbacks` option: 
 
```python
@action(is_system_action=True)
async def call_llm(user_query: str, llm: Optional[BaseLLM]) -> str:
    call_config = RunnableConfig(callbacks=[streaming_handler_var.get()])
    response = await llm.ainvoke(user_query, config=call_config)
    return response.content
``` 

There are a couple of other tweaks in the code (see the comments). Let me know if this works for you.

**Comment by msalhab96** [comment]
@drazvan Thank you for your response, tried it and it works!

**Comment by sadhulokesh** [comment]
How to add streaming through LLM to nemoguardrails to streamlit?
