### ISSUE TITLE
[Feature Request] Adding a Typescript/Javascript Wrapper or Library

### ISSUE THREAD

**Issue by abhayc-main** [NVIDIA/NeMo-Guardrails#375]
Nemo guard rails are great but it would be significantly better if there is Typescript support of any kind. I would love to see official support for TypeScript or JavaScript, ideally in the form of a wrapper or library that interfaces with NeMo Guardrails. 

As an alternative, we've considered creating our own wrapper around the Python version of NeMo Guardrails. However, this approach has its own set of challenges, including maintaining the wrapper and ensuring it stays up-to-date with the latest features and improvements in NeMo Guardrails.

If there already is or another library exists please let me know.

**Comment by drazvan** [comment]
@abhayc-main: can you share more details about your intended usage? The NeMo Guardrails server API is OpenAI compatible, so making calls from JS/TS should be straightforward. A lightweight wrapper on top of the API could be a solution. As mentioned in #38. We don't yet have planned support for JS. 

However, in case you do decide to build your own wrapper, the API should be stable enough. The effort for keeping up with the updates should be reasonable.
