### ISSUE TITLE
Prompts missing from verbose log for chat models

### ISSUE THREAD

**Issue by trebedea** [NVIDIA/NeMo-Guardrails#378]
Prompts are missing from verbose log for chat models and an warning message is shown:

`WARNING:langchain_core.callbacks.manager:Error in LoggingCallbackHandler.on_chat_model_start callback: TypeError('can only concatenate list (not "str") to list')`

**Comment by drazvan** [comment]
Thanks for the fix! Do create a PR so we can merge.
