### ISSUE TITLE
How to integrate finetuned mistral model with NeMo-Guardrails

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/NeMo-Guardrails#393]
How to integrate PEFT finetuned mistral model located in my local directory with NeMo-Guardrails.
Please share the example notebooks with sample **yaml_content** and **colang_content**

**Comment by drazvan** [comment]
@pradeepdev-1995 : What are you using to serve the model? i.e., how are you testing, from python code? HuggingFacePipeline? vLLM? Ollama? etc.

**Comment by Pouyanpi** [comment]
Closing it due to an extended period of inactivity.
