### ISSUE TITLE
Please add support for Google VertexAI Palm

### ISSUE THREAD

**Issue by raghuvd** [NVIDIA/NeMo-Guardrails#41]
Hi Team,

Please add support for Vertex AI Palm. Langchain supports it now. Please see details below.
https://python.langchain.com/en/latest/modules/models/llms/integrations/google_vertex_ai_palm.html

Currently it seems that Nemo Guardrails dependency is on langchain 0.0.167, which did not had the Vertex Palm integration. Much needed.

Thanks
Raghu

**Comment by drazvan** [comment]
Hi @raghuvd ! If you manually install the latest version of langchain, and assuming there's no breaking change, you should be able to use any newly added LLM. The list of supported ones is fetched dynamically.

**Comment by caiharry** [comment]
@raghuvd FYI, I got NeMo v0.4.0 working with PaLM with this in my `config.yml`:
```
models:
  - type: main
    engine: vertexai
    model: text-bison
```
