### ISSUE TITLE
Context is not passed into the rails.generate function

### ISSUE THREAD

**Issue by jackchan0528** [NVIDIA/NeMo-Guardrails#419]
Following the doc here: [https://github.com/NVIDIA/NeMo-Guardrails/tree/develop/docs/getting_started/7_rag](https://github.com/NVIDIA/NeMo-Guardrails/tree/develop/docs/getting_started/7_rag)
```
response = rails.generate(messages=[{
    "role": "context",
    "content": {
        "relevant_chunks": """
            Employees are eligible for the following time off:
              * Vacation: 20 days per year, accrued monthly.
              * Sick leave: 15 days per year, accrued monthly.
              * Personal days: 5 days per year, accrued monthly.
              * Paid holidays: New Year's Day, Memorial Day, Independence Day, Thanksgiving Day, Christmas Day.
              * Bereavement leave: 3 days paid leave for immediate family members, 1 day for non-immediate family members. """
    }
},{
    "role": "user",
    "content": "How many vacation days do I have per year?"
}])
print(response["content"])
```

The correct answer should be 20 days per year. However the model hallucinated and answered:

> You are entitled to 15 vacation days per year based on your current employment contract. These days accrue gradually throughout the year, so you may not have all 15 days available right at the beginning of the year. It's always a good idea to check with your HR department or refer to your employment agreement for specific details on how vacation days are accrued and how they can be used. If you have any specific plans for using your vacation days, I can help you keep track of them and even suggest some travel destinations or activities for your time off. Just let me know how I can assist you further!

I tried lots of different context and question pairs. It seems that the relevant_chunks was not passed into the entire prompt for generating the answer.

**Comment by drazvan** [comment]
@jackchan0528 : did you test with the provided notebook? (I've just tried it again and it works correctly)

**Comment by jackchan0528** [comment]
@drazvan I rerun the notebook and still get the wrong answer as 15 days per year, while the answer should be 20. You may try even simpler test cases and see that the answer generated is irrelevant to the context provided.

```
from nemoguardrails import RailsConfig, LLMRails

config = RailsConfig.from_path("./config")
rails = LLMRails(config)

response = rails.generate(messages=[{
    "role": "user",
    "content": "How many vacation days do I have per year?"
}])
print(response["content"])
```

Output:

> Fetching 7 files: 100%|██████████| 7/7 [00:00<00:00, 76858.97it/s]
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> You are entitled to 15 vacation days per year. These days can be used for any reason, such as taking a trip, spending time with family, or simply relaxing at home. It's important to plan ahead and communicate with your supervisor when you intend to take time off so that your absence can be properly accounted for. If you need any more information or assistance regarding your vacation days, feel free to ask!

nemoguardrails version: 0.8.1
config/ file contains only config.yml with content below (I tried having and removing the input & output rails for this testing):
```
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-0125
```

**Comment by drazvan** [comment]
@jackchan0528 : this is most likely because you've changed the model to `gpt-3.5-turbo-0125` (from `gpt-3.5-turbo-instruct`). Can you confirm that use the instruct version works correctly on your end?
cc @trebedea

**Comment by jackchan0528** [comment]
I tried swapping the model to gpt-3.5-turbo-instruct, by trying 5 times to generate the answers, but the model hallucinated even worse. May I understand if this never happened from your end?

**Comment by drazvan** [comment]
On my end, running the notebook as-is yields the correct result: 
<img width="690" alt="image" src="https://github.com/NVIDIA/NeMo-Guardrails/assets/206165/f4df1b17-eb4e-432c-8d8a-bb5710a00e40">

**Comment by jackchan0528** [comment]
Update: we don't even need actions.py nor blocked_terms.co. We simply need content in rails/disallowed_topics.co to yield a correct answer based on the context given
