### ISSUE TITLE
Creating new Rails and executing

### ISSUE THREAD

**Issue by ghoshaishik505** [NVIDIA/NeMo-Guardrails#43]
Hi,
I am unable to add new rails and execute them. Even if I add new rails in the example folder, it doesn't show up in the UI for Rail selection.
In v0.1.0, I could edit the existing rails of the example folder and it behaved accordingly, but after updating to v0.2.0, the changes don't reflect anymore. For Eg, if I change the config file and knowledge-base of the 'topical_rails' folder in 'Lib\site-packages\examples' folder to behave as a different Bot, it still gives answers as the default US Job Reports bot. The Langchain prompts that are executed also are of the US Job reports, even though technically I have removed all those files from the system. Clearing the '_pycache_' file also didn't help.
It is most likely that I am doing some errors.
Can someone guide me with a step-by-step process to how to create then execute a rail with examples.
Thanks in advance!

**Comment by ghoshaishik505** [comment]
@drazvan can you shed some light on this? Thanks

**Comment by drazvan** [comment]
Hi @ghoshaishik505! Changing the files in the python installation folders (e.g., `Lig\site-packages\...`) is not a good practice. To experiment with making changes to the examples, the easiest way is to clone the repository, install the dependencies (`pip install -r requirements.txt`) and then run the commands from the root of the project (make sure root is in the PYTHONPATH). Let me know if that helps.
