### ISSUE TITLE
The provider Ollama does not support streaming.

### ISSUE THREAD

**Issue by kohjx1** [NVIDIA/NeMo-Guardrails#437]
I tried referring to this [guide](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/advanced/streaming.md) and use Ollama as the engine but got this message. How do i enable streaming for Ollama-based models?

**Comment by yash-711** [comment]
To stream tokens, use the .stream(...) method:

query = "Tell me a joke"

for chunks in llm.stream(query):
    print(chunks)

https://python.langchain.com/v0.1/docs/integrations/llms/ollama/

> I tried referring to this [guide](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/advanced/streaming.md) and use Ollama as the engine but got this message. How do i enable streaming for Ollama-based models?
