### ISSUE TITLE
Issue with options in generating response

### ISSUE THREAD

**Issue by visheshgitrepo** [NVIDIA/NeMo-Guardrails#445]
Im trying to run below code.

### response = rails.generate(messages=message,options={"llm_output": True})
here, the issue arises, only if only add options as additional paramter. Not sure, if GenerationResponse is accessing index in the code.

I just pip install nemoguardrails and openai, etc and running the script.

### Getting below error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <timed exec>:19

TypeError: 'GenerationResponse' object is not subscriptable

**Comment by drazvan** [comment]
@visheshgitrepo: can you provide more details on how to reproduce?
I've tried with the snippet below and it works:

```python
from nemoguardrails import LLMRails, RailsConfig


def test_1():
    config = RailsConfig.from_content(
        colang_content="""
        define user express greeting
            "hello"

        define flow
            user express greeting
            bot express greeting
        """,
        config={
            "models": [
                {"type": "main", "engine": "openai", "model": "gpt-3.5-turbo-instruct"}
            ],
        },
    )
    rails = LLMRails(config)

    # This should not raise an exception
    response = rails.generate(
        messages=[
            {"role": "user", "content": "hi!"},
        ],
        options={"llm_output": True},
    )
    print(response)

```

**Comment by visheshgitrepo** [comment]
Please ignore this error. issue was from different line
