### ISSUE TITLE
Use default `config_id` for completions endpoint

### ISSUE THREAD

**Issue by rgstephens** [NVIDIA/NeMo-Guardrails#451]
It would be  nice if the completions endpoint was more compatible with the OpenAI endpoint so that tools that use this endpoint would work with guardrails without modification. I'd like to use the [deep-chat](https://github.com/OvidijusParsiunas/deep-chat) widget for example.

My proposal is that if neither `config_ids` nor `config_id` are provided on the completions call, the value would be set to `["config"]` as the default.

**Comment by drazvan** [comment]
Indeed. We could even use "model" as the configuration id. Thanks for the contribution!

**Comment by rgstephens** [comment]
For my use case, the "model" value need to be empty.
