### ISSUE TITLE
Custom LLM Models using langchain BaseLanguageModel

### ISSUE THREAD

**Issue by uvnikgupta** [NVIDIA/NeMo-Guardrails#458]
I tried to find an example of creating custom LLM model using `BaseLanguageModel` as mentioned in the docs at  https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md#supported-llm-models. In an earlier discussion thread @drazvan provided a link to https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/llm/providers/nemollm.py that uses `BaseLLM` and `BaseModel`. Can someone please point me to example I can refer for creating the custom LLM as per the documentation?

**Comment by Pouyanpi** [comment]
Hi @uvnikgupta ,

From technical perspective It does not really matter, you can extend the `BaseLanguageModel` as mentioned in the documentation or ` BaseLLM` even you can extend the  `LLM` class from langchain.
```python 

# Just a high level sketch

from langchain_core.language_models.llms import LLM

class MyCustomLLM(LLM):
    async def _acall(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs,
    ) -> str:
        pass

     def _call(
      self,
      prompt: str,
      stop: Optional[List[str]] = None,
      run_manager: Optional[CallbackManagerForLLMRun] = None,
      **kwargs,
      ) -> str:
        pass
        # required to implement
        
      def _stream(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
       ) -> Iterator[GenerationChunk]:
         pass
         #Optional to implement
         
    # rest of the implementation
....

```

The more important thing is to implement the interface:

Required:

- `_call`
- `_llm_type`

Optional:

- `_acall`
- `_astream`
- `_stream`
- `_identifying_params`

Better to chose the base class that is compatible with your installed dependencies.

Let me know if you need further assistance.

Best,
Pouyan

**Comment by uvnikgupta** [comment]
@Pouyanpi , thanks for the response. I have used the Nemo llm to replicate my custom LLM
