### ISSUE TITLE
use custom embedding and llm

### ISSUE THREAD

**Issue by sampratha28** [NVIDIA/NeMo-Guardrails#466]
I want to use custom embedding and custom llm (which are bascally API endpoints )to integrate with nemo guardrails.
I already have it implemented in langchain.
how do i use it with nemo guardrails?

**Comment by Pouyanpi** [comment]
Hi @sampratha28 ,

Have you followed the documentation? Specially you might find these documents helpful:

* [Custom LLM](https://github.com/NVIDIA/NeMo-Guardrails/blob/9e65111b036e0b0073c27b8fdc0b20ad087593f9/docs/user_guides/configuration-guide.md?plain=1#L159)
* [Custom Embedding Search Provider](https://github.com/NVIDIA/NeMo-Guardrails/blob/9e65111b036e0b0073c27b8fdc0b20ad087593f9/docs/user_guides/advanced/embedding-search-providers.md?plain=1#L78)

You can look at some example implementations here:
* [Embedding Providers](https://github.com/NVIDIA/NeMo-Guardrails/tree/9e65111b036e0b0073c27b8fdc0b20ad087593f9/nemoguardrails/embeddings/embedding_providers)
* [Custom LLM](https://github.com/NVIDIA/NeMo-Guardrails/tree/9e65111b036e0b0073c27b8fdc0b20ad087593f9/nemoguardrails/llm/providers)

Let me know if you need further assistance.

Thanks!
Pouyan
