### ISSUE TITLE
How to run the examples in llm dolly

### ISSUE THREAD

**Issue by JINO-ROHIT** [NVIDIA/NeMo-Guardrails#469]
I keep running into this error, how to run the guardrail with dolly?

Exception: Unknown LLM engine: hf_pipeline_dolly.

**Comment by Pouyanpi** [comment]
If you are still experiencing the issue, please open a new one and reference this one. We now use issue templates that can help provide the necessary information. Unfortunately, the current issue lacks sufficient details for us to address it. Thank you!
