### ISSUE TITLE
How to save and load conversation history ?

### ISSUE THREAD

**Issue by cyun9601** [NVIDIA/NeMo-Guardrails#475]
Hello. 
I have a question about managing conversation history.
I want to save the history and state of an ongoing conversation, recall an existing conversation based on a key value, and continue the next conversation. Does nemoguardrails provide that functionality ?

**Comment by drazvan** [comment]
Hi @cyun9601!
Is this what you're looking for: https://github.com/NVIDIA/NeMo-Guardrails/blob/main/docs/user_guides/server-guide.md#threads?
