### ISSUE TITLE
How to use streaming response?

### ISSUE THREAD

**Issue by YoshitakaOyama** [NVIDIA/NeMo-Guardrails#48]
First of all, thank you for doing a great library development.
It's very cool and easy to use and we would like to incorporate it into our chatbot projects!

But I would like to use the ability to generate answers in real time. Equivalent to openai ```stream``` option.
How to use it ...?

**Comment by drazvan** [comment]
Hi @YoshitakaOyama ! Streaming is challenging (see https://github.com/NVIDIA/NeMo-Guardrails/discussions/15). It's on our roadmap but we don't yet have an ETA for when we'll ship updates related to this.

**Comment by YoshitakaOyama** [comment]
Hi @drazvan!
ok, got it.
I hope it will be implemented soon.
Thank you for your answer!

**Comment by Sassun** [comment]
Any updates on this?

**Comment by closedLoop** [comment]
I think a minimal requirement would be to enable steaming (via SSE) of:

- [ ] The last response in a flow
- [ ] Optionally some data related to the actions being taken by the agent
