### ISSUE TITLE
Vulnerabilities in the dependent packages for nemogaurdrails package.

### ISSUE THREAD

**Issue by koushikv** [NVIDIA/NeMo-Guardrails#49]
Hello,

Firstly thank-you for this great library. 
But when i tried to do a pip install I'm seeing some vulnerable packages with high severity level are getting downloaded for example:

Package Name: starlette
Package version: 0.26.1
 Issue: it has a high severity vulnerability which was fixed in pater version 0.27.0 or higher 
CVE code: SNYK-PYTHON-STARLETTE-5538332

Package Name: requests
Package version: 2.28.2
Issue: it has s medium severity vulnerability which was fixed in 2.31.2
CVE Code: SNYK-PYTHON-REQUESTS-5595532

So wanted to check if there is any plan to upgrade the versions of the above modules to fix the vulnerabilities?

Thanks in advance

**Comment by drazvan** [comment]
Hi @koushikv! Yes, for the release at the end of this month, we will upgrade the packages you mentioned.

**Comment by drazvan** [comment]
This is now fixed. Thanks again @koushikv for reporting!
