### ISSUE TITLE
Input guardrails error

### ISSUE THREAD

**Issue by javixeneize** [NVIDIA/NeMo-Guardrails#490]
Hi

Im having some issues when creating input guardrails

I am just replicating what is in the guide, https://github.com/NVIDIA/NeMo-Guardrails/tree/develop/docs/getting_started/4_input_rails/config and it works fine. 

However, when i do any change to the names, it is, change the name to self_check_input2, it doesnt work

I have modified the following files:

config.yaml

rails:
  input:
    flows:
      - self check input2

prompts.yaml

prompts:
  - task: self_check_input2
    content: |

config.co

define flow self check input2
  $allowed = execute self_check_input2

  if not $allowed
    bot polite answer
    stop

When executing it, i have this error

Action 'self_check_input2' not found.

Any idea what might be the problem?

Thanks

**Comment by Pouyanpi** [comment]
Hi @javixeneize,

Yes, you must define an action called `self_check_input2` the reason that the guide works is that the `self_check_input` action is defined at https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/self_check/input_check/actions.py 

so the execute fails as there is no `self_check_input2` defined.

changing it to will work

```colang
define flow self check input2
  $allowed = execute self_check_input

  if not $allowed
    bot polite answer
    stop
 ```
