### ISSUE TITLE
Instance of embedding search provider in action

### ISSUE THREAD

**Issue by uvnikgupta** [NVIDIA/NeMo-Guardrails#498]
I have a custom embeddings search provider that that replicates the BasicEmbeddingsIndex but uses a Vector DB instead of ANNOY. I have loaded some documents in this DB and want to perform a RAG operation based on user utterances. I do not want to use an instance of the knowledge_base because the documents are not available in the kb folder and hence the knowledge_base is never initialized. I want to retrieve the documents directly from the vector store for which I need an instance of the custom embedding search provider in my action method.  

The config.core.embeddings_searh_provider provides only the instance of EmbeddingsSearchProvider instance created from the config file it does contain the instance of the actual embeddings search provider class. This can be created using LLMRails._get_embeddings_search_provider() method but LLMRails instance is not passed to the action method. 

So can someone please tell me how to solve this issue.

**Comment by drazvan** [comment]
Hi @uvnikgupta!

I'm not sure I fully understand, but let me try to make a few suggestions. 

1. You could, as a workaround, just add a `kb` folder in the config with an empty `.md` file (or with one sentence in it). This should trigger the initialization of the KB. I assume your embedding search provider will not do anything when instructed to build the index, as it will connect to a pre-built one. 
2. You can override the `retrieve_relevant_chunks` action directly and perform the search using your vector DB in there, so without going through the embedding search provider mechanism. 

Let me know if this is helpful.

**Comment by uvnikgupta** [comment]
@drazvan, thank for your response.
In the meantime I could resolve this issue by registering the rails instance as an action parameter. But I think the solutions you provided are cleaner. Maybe I will try to change my code to see which of the suggested methods work

**Comment by drazvan** [comment]
That's an interesting solution, to register the `LLMRails` instance itself as an action parameter.
