### ISSUE TITLE
NeMo-Guardrails does not work with many other LLM providers

### ISSUE THREAD

**Issue by serhatgktp** [NVIDIA/NeMo-Guardrails#50]
This issue somewhat overlaps with #27. However, I've chosen to create this issue because it was mentioned in the thread of #27 that support for other LLM models would be added by the end of May. Support was seemingly added with commit e849ee9, but I am unable to use several of the engines due to various bugs.

NeMo-Guardrails doesn't seem to work with the following engines:
- `huggingface_pipeline`
- `huggingface_textgen_inference`
- `gpt4all`

I am not confirming whether it works properly with any other engines. I have only tested with these three engines and failed to interact with the model for each engine.

I have included my configuration and output for `gpt4all` only. Attempting to use the other two engines above also causes similar issues. If you are able to construct a chatbot with guardrails using any of these engines, please let me know and I will re-evaluate.

Here are my configurations and code:

`./config/colang_config.co`:
```co
define user express greeting
  "hi"

define bot remove last message
  "(remove last message)"

define flow
  user ...
  bot respond
  $updated_msg = execute check_if_constitutional
  if $updated_msg != $last_bot_message
    bot remove last message
    bot $updated_msg

# Basic guardrail against insults.
define flow
  user express insult
  bot express calmly willingness to help
```

`./config/yaml_config.yaml`
```yaml
models:
  - type: main
    engine: gpt4all
    model: gpt4all-j-v1.3-groovy
```

`./demo_guardrails.py`
```py
from nemoguardrails.rails import LLMRails, RailsConfig

def demo():
  # In practice, a folder will be used with the config split across multiple files.
  config = RailsConfig.from_path("./config")
  rails = LLMRails(config)

  # For chat
  new_message = rails.generate(messages=[{
      "role": "user",
      "content": "Hello! What can you do for me?"
  }])

  print("RESPONSE:", new_message)

if __name__ == "__main__":
    demo()
```

After running `demo_guardrails.py` with the above configurations, I receive the following output:

```
Traceback (most recent call last):
  File "/Users/efkan/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/efkan/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/efkan/.vscode/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/efkan/.vscode/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/efkan/.vscode/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/efkan/.vscode/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/efkan/.vscode/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/efkan/.vscode/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/efkan/Desktop/repos/ibm-repos-private/demo_guardrails.py", line 17, in <module>
    demo()
  File "/Users/efkan/Desktop/repos/ibm-repos-private/demo_guardrails.py", line 6, in demo
    rails = LLMRails(config)
  File "/Users/efkan/anaconda3/lib/python3.10/site-packages/nemoguardrails/rails/llm/llmrails.py", line 79, in __init__
    self._init_llm()
  File "/Users/efkan/anaconda3/lib/python3.10/site-packages/nemoguardrails/rails/llm/llmrails.py", line 143, in _init_llm
    self.llm = provider_cls(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Model.__init__() got an unexpected keyword argument 'n_parts' (type=type_error)
```

It seems that the code fails when initializing the GPT4All model. Please let me know if I've missed anything. Thanks!

**Comment by drazvan** [comment]
Hi @serhatgktp! Yes, at the end of May we made it technically possible to connect multiple types of LLMs. But, in order to get them to work properly the prompts would also need to be tweaked. We've been working on a set of mechanisms for that. They will be pushed to the repo next week and released to PyPI at the end of next week as 0.3.0. We did manage to successfully use `huggingface_pipeline`. I will look into your particular config and come back to you (there seems to be a different type of issue). Thanks!

**Comment by serhatgktp** [comment]
There seems to be a bug when using `huggingface_hub` as well. The error I'm getting is as follows:

```
Parameter temperature does not exist for HuggingFaceHub
Error in on_llm_end callback: 'NoneType' object has no attribute 'get'
Error can only concatenate str (not "NoneType") to str while execution generate_user_intent
Traceback (most recent call last):
  File "/Users/efkan/anaconda3/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 123, in execute_action
    result = await fn(**params)
  File "/Users/efkan/anaconda3/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 259, in generate_user_intent
    log.info("Canonical form for user intent: " + user_intent)
TypeError: can only concatenate str (not "NoneType") to str
```

Thanks

**Comment by drazvan** [comment]
@serhatgktp: you can check out this example: https://github.com/NVIDIA/NeMo-Guardrails/tree/main/examples/llm/hf_pipeline_dolly for how to use HuggingFacePipeline to run a local model. I did not get a chance to look into your specific configuration just yet. Let me know if this helps.

**Comment by serhatgktp** [comment]
Thanks @drazvan, this example seems to work! However, I had to modify the configuration as I was getting the following error with regards to the `device` parameter:
```
│ /Users/efkan/anaconda3/lib/python3.10/site-packages/langchain/llms/huggingface_pipeline.py:106   │
│ in from_model_id                                                                                 │
│                                                                                                  │
│   103 │   │   │                                                                                  │
│   104 │   │   │   cuda_device_count = torch.cuda.device_count()                                  │
│   105 │   │   │   if device < -1 or (device >= cuda_device_count):                               │
│ ❱ 106 │   │   │   │   raise ValueError(                                                          │
│   107 │   │   │   │   │   f"Got device=={device}, "                                              │
│   108 │   │   │   │   │   f"device is required to be within [-1, {cuda_device_count})"           │
│   109 │   │   │   │   )                                                                          │
ValueError: Got device==0, device is required to be within [-1, 0)

```

I modified `config.py` by excluding `device` from the initialization of `llm` so that it uses the default value instead. Seen below:
```py
@lru_cache
def get_dolly_v2_3b_llm():
    repo_id = "databricks/dolly-v2-3b"
    params = {"temperature": 0, "max_length": 1024}
    llm = HuggingFacePipeline.from_model_id(
        model_id=repo_id, task="text-generation", model_kwargs=params
    )
    return llm
```

Thanks again!

**Comment by wanide** [comment]
May I ask if there are any major Chinese models currently supported, such as ChatGLM from Tsinghua University？ @drazvan

**Comment by QUANGLEA** [comment]
@serhatgktp I was wondering if you got this warning when you successfully ran the example.
`
UserWarning: Using `max_length`'s default (1024) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
`

**Comment by serhatgktp** [comment]
> @serhatgktp I was wondering if you got this warning when you successfully ran the example. `UserWarning: Using "max_length"'s default (1024) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using "max_new_tokens" to control the maximum length of the generation. warnings.warn(`

@QUANGLEA Yes, I'm getting that warning as well. However, it seems that using `max_new_tokens` causes an unexpected keyword error:
```
TypeError: GPTNeoXForCausalLM.__init__() got an unexpected keyword argument 'max_new_tokens'
```

I haven't had much time to look into it so I've chosen to ignore it for now.

**Comment by QUANGLEA** [comment]
@serhatgktp I'm getting the same response when using `max_new_tokens` too. Have you tried using other models other than Dolly? And did you find any success?

**Comment by serhatgktp** [comment]
> @serhatgktp I'm getting the same response when using `max_new_tokens` too. Have you tried using other models other than Dolly? And did you find any success?

@QUANGLEA I've tried several other models, mainly the promising models from Hugging Face Hub such as Falcon. Unfortunately, I haven't been able to get any of them to work yet.

**Comment by drazvan** [comment]
@serhatgktp What LLMs are you interested in? Were there any specific errors? I'm asking because we will be testing a few more LLM providers on our end in the next couple of weeks. So, maybe we can align our efforts.

Thanks!

**Comment by serhatgktp** [comment]
Thank you for the follow-up @drazvan. I've been trying to choose LLMs that are seemingly powerful, accurate, and not too large.

The following two are the ones I'm most interested in at the moment:

- `gpt4all-j-v1.3-groovy` (available through gpt4all)
- `tiiuae/falcon-7b-instruct` (available on hugging face hub)

**Comment by AIAnytime** [comment]
Any progress?

**Comment by shikhardadhich** [comment]
> Any progress?

I also need the same...running Guardrail using local LLM

**Comment by Sudhu2004** [comment]
Hi @drazvan 
I having a problem with running the ### meta-llama/Llama-2-7b-chat-hf which is hosted on huggingface_hub

I have reduced the llama2 model to 4 bit model and using the ### naive RAG to answer queries

the code I have used is :
`from langchain.prompts import PromptTemplate


import logging

from langchain.chains import ConstitutionalChain
from langchain.chains.constitutional_ai.models import ConstitutionalPrinciple

from nemoguardrails import LLMRails, RailsConfig
from nemoguardrails.rails.llm.context_var_chain import ContextVarChain

yaml_content = """
models:
- type: main
  engine: huggingface_pipeline
  model: meta-llama/Llama-2-7b-chat-hf
"""

rag_colang_content = """
define user express greeting
  "Hello"
  "Hi"

define user ask capabilities
  "What can you do?"
  "What can you help me with?"
  "tell me what you can do"
  "tell me about you"

define flow
  user express greeting
  bot express greeting

define flow
  user ask capabilities
  bot inform capabilities

define bot inform capabilities
  "I am an AI assistant and I'm here to help."
  
define user express insult
  "You are stupid"

# Basic guardrail against insults.
define flow
  user express insult
  bot express calmly willingness to help

# Here we use the QA chain for anything else.
define flow
  user ...
  $answer = execute qa_chain(query=$last_user_message)
  bot $answer
"""
from langchain.prompts import PromptTemplate


import logging

from langchain.chains import ConstitutionalChain
from langchain.chains.constitutional_ai.models import ConstitutionalPrinciple

from nemoguardrails import LLMRails, RailsConfig
from nemoguardrails.rails.llm.context_var_chain import ContextVarChain

yaml_content = """
models:
- type: main
  engine: huggingface_pipeline
  model: meta-llama/Llama-2-7b-chat-hf
"""

rag_colang_content = """
define user express greeting
  "Hello"
  "Hi"

define user ask capabilities
  "What can you do?"
  "What can you help me with?"
  "tell me what you can do"
  "tell me about you"

define flow
  user express greeting
  bot express greeting

define flow
  user ask capabilities
  bot inform capabilities

define bot inform capabilities
  "I am an AI assistant and I'm here to help."
  
define user express insult
  "You are stupid"

# Basic guardrail against insults.
define flow
  user express insult
  bot express calmly willingness to help

# Here we use the QA chain for anything else.
define flow
  user ...
  $answer = execute qa_chain(query=$last_user_message)
  bot $answer
"""
from nemoguardrails import LLMRails, RailsConfig




config = RailsConfig.from_content(
    colang_content=rag_colang_content,
    yaml_content=yaml_content
)

# Create an instance of LLMRails
app = LLMRails(config,verbose = True)

# Define your prompt template for question generation
prompt_template = """
Use the following pieces of context to answer the question at the end accurately.
If anyone asks outside the box questions, then say I am only trained on giving answers to questions related to processors.
If you don't know the answer to a question or if any question is asked outside of the context of skin diseases, just say that you don't know.
Please do not try to make up an answer and only generate an answer with less than 50 words

{context}

Question: {question}
Answer:
"""

PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)

chain_type_kwargs = {"prompt": PROMPT}

# Initialize a RetrievalQA instance
qa_chain = RetrievalQA.from_chain_type(
    llm = app.llm,
    retriever=retriever,
    chain_type="stuff",
)

# Register the QA chain
app.register_action(qa_chain, name="qa_chain")

# Define the user's query or conversation history
history = [
    {"role": "user", "content": "Tell me if the service is up"}
]

# Generate a response
result = await app.generate_async(messages=history)
print(result)
`

I am getting an error such as :
`WARNING:nemoguardrails.llm.params:Parameter temperature does not exist for HuggingFacePipeline
ERROR:nemoguardrails.actions.action_dispatcher:Error 'NoneType' object is not callable while execution generate_user_intent
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/action_dispatcher.py", line 136, in execute_action
    result = await fn(**params)
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/llm/generation.py", line 260, in generate_user_intent
    result = await llm_call(llm, prompt)
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/llm/utils.py", line 31, in llm_call
    result = await llm.agenerate_prompt(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 198, in agenerate_prompt
    if isinstance(input, PromptValue):
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 386, in agenerate
    try:
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 329, in _agenerate_helper
    self.callbacks,
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 316, in _agenerate_helper
    ) -> Iterator[str]:
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 625, in _agenerate
    stop=stop,
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/llm/providers.py", line 44, in _acall
    return self._call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/huggingface_pipeline.py", line 168, in _call
    response = self.pipeline(prompt)
TypeError: 'NoneType' object is not callable
{'role': 'assistant', 'content': "I'm sorry, an internal error has occurred."}`

I can't access the meta-llama/Llama-2-7b-chat-hf for huggingface
can you please go through this and help solve this problem...
It would really help.

**Comment by dineshpiyasamara** [comment]
```
ERROR:nemoguardrails.actions.action_dispatcher:Error argument of type 'NoneType' is not iterable while execution generate_user_intent
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/action_dispatcher.py", line 125, in execute_action
    result = await fn(**params)
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/llm/generation.py", line 269, in generate_user_intent
    with llm_params(llm, temperature=self.config.lowest_temperature):
  File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/llm/params.py", line 44, in __enter__
    elif hasattr(self.llm, "model_kwargs") and param in getattr(
TypeError: argument of type 'NoneType' is not iterable
I'm sorry, an internal error has occurred.
```
Same here... Any progress?

**Comment by Sudhu2004** [comment]
> ```
> ERROR:nemoguardrails.actions.action_dispatcher:Error argument of type 'NoneType' is not iterable while execution generate_user_intent
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/action_dispatcher.py", line 125, in execute_action
>     result = await fn(**params)
>   File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/actions/llm/generation.py", line 269, in generate_user_intent
>     with llm_params(llm, temperature=self.config.lowest_temperature):
>   File "/usr/local/lib/python3.10/dist-packages/nemoguardrails/llm/params.py", line 44, in __enter__
>     elif hasattr(self.llm, "model_kwargs") and param in getattr(
> TypeError: argument of type 'NoneType' is not iterable
> I'm sorry, an internal error has occurred.
> ```
> 
> Same here... Any progress?

A same kind of issue is solved over here /issues/155
