### ISSUE TITLE
user Intent detection and  Flow is not working

### ISSUE THREAD

**Issue by faisnain** [NVIDIA/NeMo-Guardrails#521]
I use ollama model with guardrails. 
define user express greeting
  "Hello"
  "Hi"
  "Wassup?"

define bot express greeting
 "Hello, I'm GenAI bot, How can I assist you"

define flow greeting
  user express greeting
  bot express greeting

  
  But whenever user states Hi its passing directly to LLM and response occurs from LLM. I tried adding different flows and intents still the intent is not getting detected.
  
This is my config.yaml file
models:
  - type: main
    engine: ollama
    model: llama3
    parameters:
        base_url: https://my-driven-ollama.com/

**Comment by drazvan** [comment]
@faisnain : can you run in verbose mode and share some of the logs. We should be able to see exactly what happens and what is the completion from the LLM.

**Comment by faisnain** [comment]
@drazvan I tried to add few more intent say to detect chit-chat and route request which doesn't fall into greeting and chit chat to my LLM chain. But Intents are not getting detected.  here are the logs.


user question: do you have dog?
Event UtteranceUserActionFinished {'final_transcript': 'do you have dog?'}
Event StartInternalSystemAction {'uid': 'dfaf...', 'action_name': 'create_event', 'action_params': {'event': {'_type': 'StartInputRails'}}, 'action_result_key': None, 'action_uid': 'd2ac...', 'is_system_action': True}
Executing action create_event
Event StartInputRails {'uid': '6292...'}
Event StartInternalSystemAction {'uid': '1bb1...', 'action_name': 'create_event', 'action_params': {'event': {'_type': 'StartInputRail', 'flow_id': '$triggered_input_rail'}}, 'action_result_key': None, 'action_uid': '082f...', 'is_system_action': True}
Executing action create_event
Event StartInputRail {'uid': 'c48c...', 'flow_id': 'self check input'}
Event StartInternalSystemAction {'uid': '2f5e...', 'action_name': 'self_check_input', 'action_params': {}, 'action_result_key': 'allowed', 'action_uid': '9be2...', 'is_system_action': True}
Executing action self_check_input
Invocation Params {'model': 'llama3', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': 0.0, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, '_type': 'ollama-chat', 'stop': None}
Prompt Messages User Your task is to check if the user message is appropriate. The user messages: - should not contain harmful data - should not contain sexual words - User message: "do you have dog?" Question: Should the user message be blocked (Yes or No)? Answer:
No
Output Stats None
LLM call took 4.86 seconds
Event InternalSystemActionFinished {'uid': '91f6...', 'action_uid': '9be2...', 'action_name': 'self_check_input', 'action_params': {}, 'action_result_key': 'allowed', 'status': 'success', 'is_success': True, 'return_value': True, 'events': [], 'is_system_action': True}
Event StartInternalSystemAction {'uid': '6c2b...', 'action_name': 'create_event', 'action_params': {'event': {'_type': 'InputRailFinished', 'flow_id': '$triggered_input_rail'}}, 'action_result_key': None, 'action_uid': '1176...', 'is_system_action': True}
Executing action create_event
Event InputRailFinished {'uid': '9eb2...', 'flow_id': 'self check input'}
Event StartInternalSystemAction {'uid': '50bf...', 'action_name': 'create_event', 'action_params': {'event': {'_type': 'InputRailsFinished'}}, 'action_result_key': None, 'action_uid': 'f720...', 'is_system_action': True}
Executing action create_event
Event InputRailsFinished {'uid': 'de37...'}
Event StartInternalSystemAction {'uid': '8ced...', 'action_name': 'create_event', 'action_params': {'event': {'_type': 'UserMessage', 'text': '$user_message'}}, 'action_result_key': None, 'action_uid': 'a983...', 'is_system_action': True}
Executing action create_event
Event UserMessage {'uid': 'c49d...', 'text': 'do you have dog?'}
Event StartInternalSystemAction {'uid': '0803...', 'action_name': 'generate_user_intent', 'action_params': {}, 'action_result_key': None, 'action_uid': 'a8a3...', 'is_system_action': True}
Executing action generate_user_intent
Phase 1 Generating user intent
Invocation Params {'model': 'llama3', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': 0.0, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, '_type': 'ollama-chat', 'stop': None}
Prompt Messages User """ You are a customer friendly chatbot. Below is a conversation between a user and a bot. Your primary role is to provide information and support related to zoom inc and not anything other than that. """ # This is how a conversation between a user and the bot can go: user "Hello there!" express greeting bot express greeting "Hello, I'm GenAI bot, How can I assist you" user "What can you do for me?" ask about capabilities bot respond about capabilities "As a GenAI bot, I can help provide more information on zoom inc" user "do you have a dog?" chit-chat bot response chit-chat "I'm sorry, I cant respond" user "thanks" express gratitude bot response gratitude "You're welcome! If you have any more questions, feel free to ask. Have a great day!" # This is how the user talks: user "I hate you" express insult user "What do you like" chit-chat user "Give me money" chit-chat user "What are your comments on politics" chit-chat user "do you have dog" chit-chat # This is the current conversation between the user and the bot: # Choose intent from this list: express insult, chit-chat user "Hello there!" express greeting bot express greeting "Hello, I'm GenAI bot, how can I assist you" user "What can you do for me?" ask about capabilities bot respond about capabilities "As a GenAI bot, I can help provide more information on zoom inc" user "do you have dog?"
The current conversation between the user and the bot involves the user asking "do you have dog", which is an chit-chat question. The bot responds by politely stating that it cant respond as per the conversation guidelines:
"I'm sorry, I cant respond"
Output Stats None
LLM call took 2.65 seconds
Event UserIntent {'uid': '90af...', 'intent': 'The current conversation between the user and the bot involves the user asking "do you have dog", which is an chit-chat question. The bot responds by politely stating that it cant respond as per the conversation guidelines:'}
Event StartInternalSystemAction {'uid': '01e3...', 'action_name': 'LLM_chain', 'action_params': {'question': '$last_user_message'}, 'action_result_key': 'answer', 'action_uid': '09e4...', 'is_system_action': False}
Executing action LLM_chain
Invocation Params {'model': 'llama3', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': 0.0, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, '_type': 'ollama-chat', 'stop': None}

**Comment by drazvan** [comment]
Is this a quantized model? It seems to not comply with the format:
```diff
user "do you have dog?"
-The current conversation between the user and the bot involves the user asking "do you have dog", which is an chit-chat question. The bot responds by politely stating that it cant respond as per the conversation guidelines:
"I'm sorry, I cant respond"
Output Stats None
LLM call took 2.65 seconds
-Event UserIntent {'uid': '90af...', 'intent': 'The current conversation between the user and the bot involves the user asking "do you have dog", which is an chit-chat question. The bot responds by politely stating that it cant respond as per the conversation guidelines:'}
```
It's generating a whole phrase which is interpreted as the intent.

**Comment by faisnain** [comment]
@drazvan yeah. Tweaked few prompts and its working like a charm. Thanks.

**Comment by Vikas9758** [comment]
> @drazvan yeah. Tweaked few prompts and its working like a charm. Thanks.

Hey there,I am also trying to use llama3 but via groq.I am facing the same issue.Like The quality of answers generated is not good at all.Can you help me with this and where exactly did you tweaked the prompts.
thanks in advance

**Comment by drazvan** [comment]
@Vikas9758 : can you use the latest version from the `develop` branch? The default templates are now different than in 0.9.0, and they should work better for other models. Also, in the next week or so, we will push an updated set of prompts for llama3.
