### ISSUE TITLE
How to add prompts.yml contents in RailsConfig.from_content() configuration

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/NeMo-Guardrails#522]
I am using the following off topic checking guard rail

```
from nemoguardrails import RailsConfig
yaml_content = """
instructions:
  - type: general
    content: |
      You are an AI assistant 
rails:
  dialog:
    user_messages:
      embeddings_only: True
"""
colang_content="""
define user ask off topic
    "How to create a dataset in Lumin"
    "Different types of uses in Lumin"
    "steps to publish a solution in lumin"
define bot explain cant off topic
    "True"

define flow
    user ask off topic
    bot explain cant off topic
"""
define user ask off topic
config = RailsConfig.from_content(
    yaml_content=yaml_content,
    colang_content=colang_content
)
```

Now I want to add the input rail also to this configuration for jailbreak detection - I have **prompts.yml** file. So where can I specify the  **prompts.yml** contents in the above ```RailsConfig.from_content()``` configuration?

Note : It is possible using ```RailsConfig.from_path(config_path)``` where **config_path** is the folder containing all prompts.yml,config.yml and offtopic.co..etc.
But now I want to implement this using **RailsConfig.from_content()** method.

**Comment by faisnain** [comment]
You can add the contents of prompts.yml in the yaml_content itself.

**Comment by drazvan** [comment]
Yes, @faisnain is right. All the .yml content can be joined into a single `yaml_content`. In fact, even in the files you can put the prompts inside the `config.yml` file, for example. The recommended way is to keep them separate for readability.
