### ISSUE TITLE
Support langchain 0.2.*

### ISSUE THREAD

**Issue by jesnie** [NVIDIA/NeMo-Guardrails#523]
The newest version of langchain is `0.2.*`, but you require `langchain<0.2.0`.

It would be really nice if you could support the newest version of langchain, so that we can install your library alongside the newest version of langchain, and take advantage of the bugfixes and new features in that.

**Comment by drazvan** [comment]
Hi @jesnie! If nothing breaks, we should be able to add support smoothly.

**Comment by Pouyanpi** [comment]
Hi @jesnie,

I’m closing this issue as it has been resolved by #551.

**Comment by cbornet** [comment]
This is an important fix. Will there be a release soon ?

**Comment by drazvan** [comment]
The next release is scheduled for the end of the month, but it's looking like it's going to slip a bit into July. If that's the case, we'll consider doing a patch release (0.9.1) towards the end of the month.

**Comment by cbornet** [comment]
Thanks for the info.

**Comment by cbornet** [comment]
Hi @drazvan . Could there be a patch release for this if the next release is delayed ?
