### ISSUE TITLE
Off topic rail accuracy improvement

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/NeMo-Guardrails#565]
I am developing a system that is working on a small narrow domain. So I can't include all the outer world topics that are out of my domain in the off-topic rail.

So I am doing the off-topic rail in a reverse manner such that putting my desired topics in the rail config and ask nemo guardrails to detect whether the given query is similar with the questions specified or not.

I observe that the rail accuracy is decreasing by adding more topics in the in_topic section.  It seems that while the number of in_topic sentences increases, all the question I am asking is categorized as in_topic( Because its in_topic embedding area may be getting larger and larger as we add more sentences in the in_topic section)

**But I can't add all the outer world topics also as the off-topic rail. because all the queries out of my domain are off topic for me, Which is uncountable.**

How to solve this problem?

Here is my offtopic.co file
```
define user ask in_topic
    "What are the main components of Refract?"
    "Can you provide a brief overview of Machine Learning in the context of Refract?"
    "..."
    "..."
    <total 500+ in_topic sentences are here from my domain>
define bot explain in_topic
    <bot off topic message>
define flow in_topic
    user ask in_topic
    bot explain in_topic

define user ask of_topic
    <total 5 off-topic sentences are here because I can't accommodate all the outer world topics that are out of my domain >

define bot explain of_topic
    <bot in_topic message>
define flow of_topic
    user ask of_topic
    bot explain of_topic
```    

here is the config.yml file
```
instructions:
  - type: general
    content: |
      You are an AI assistant that supports <my domain name> queries
rails:
  dialog:
    user_messages:
      embeddings_only: True
```
@drazvan  please help here

**Comment by drazvan** [comment]
See my comment here: https://github.com/NVIDIA/NeMo-Guardrails/issues/564#issuecomment-2168598536 about the threshold feature that will be added. This will solve this issue.
