### ISSUE TITLE
Parameter temperature does not exist

### ISSUE THREAD

**Issue by QUANGLEA** [NVIDIA/NeMo-Guardrails#57]
I'm trying to integrate HuggingFace models with this framework. I'm currently using HuggingFaceHub() as my LLM using a similar structure to the [example](https://github.com/NVIDIA/NeMo-Guardrails/blob/main/examples/llm/hf_pipeline_dolly/config.py). However, I keep getting the errors: 

`WARNING:nemoguardrails.llm.params:Parameter temperature does not exist for WrapperLLM
WARNING:langchain.callbacks.manager:Error in on_llm_end callback: 'NoneType' object has no attribute 'get'
ERROR:nemoguardrails.actions.action_dispatcher:Error can only concatenate str (not "NoneType") to str while execution generate_user_intent`

**Comment by serhatgktp** [comment]
This looks like it could be due to a bug that was solved with #51. Could you confirm whether you have the latest version of nemoguardrails?

```bash
pip install --upgrade nemoguardrails
```

**Comment by QUANGLEA** [comment]
@serhatgktp I already updated the package to the latest version.
