### ISSUE TITLE
passing in relevant_chunks as a message's context

### ISSUE THREAD

**Issue by johnyoonh** [NVIDIA/NeMo-Guardrails#575]
[In the Rag example, passing in the relevant_chunks as a message is possible](https://github.com/NVIDIA/NeMo-Guardrails/blob/26304fd0bbf51f2c0c8ca0cb1ed242775f45dfe3/docs/getting_started/7_rag/rag.ipynb#L203)
```
response = rails.generate(messages=[{
    "role": "context",
    "content": {
        "relevant_chunks": """
            Employees are eligible for the following time off:
              * Vacation: 20 days per year, accrued monthly.
              * Sick leave: 15 days per year, accrued monthly.
              * Personal days: 5 days per year, accrued monthly.
              * Paid holidays: New Year's Day, Memorial Day, Independence Day, Thanksgiving Day, Christmas Day.
              * Bereavement leave: 3 days paid leave for immediate family members, 1 day for non-immediate family members. """
    }
}]
```
But when trying this as a JSON input, the `relevant_chunks` will trigger ContextUpdate and make the state update to stop, ending the event chain to be incomplete and input request failing silently with empty response.

Here is my current workaround, where I try to treat context update for  `relevant_chunks` as other types of event, so that `new_state` is created and event chain is continued:
[nemoguardrails/colang/v1_0/runtime/flows.py](https://github.com/NVIDIA/NeMo-Guardrails/blob/26304fd0bbf51f2c0c8ca0cb1ed242775f45dfe3/nemoguardrails/colang/v1_0/runtime/flows.py#L349)
```
    # We don't need to decide any next step on context updates.
    if event["type"] == "ContextUpdate":
        # TODO: add support to also remove keys from the context.
        #  maybe with a special context key e.g. "__remove__": ["key1", "key2"]
        state.context.update({"context": event["data"]})
        if not 'relevant_chunks' in event["data"]:
            state.context.update(event["data"])
            state.context_updates = {}
            state.next_step = None
            return state
```

My proposed solution is to allow for custom role and update the context with consistent name pattern: "user_message", "context_message", "assistant_message", "custom_message",  etc

This would allow me to pass in context specific message like this:
```
[{
    "role": "context",
    "content": "I am context content"
    },
{
    "role": "custom",
    "content": "I am content for custom role"
    }
    ]
```

In an action, I would be able to retrieve them like this: `context_message = context.get("context_message")`

**Comment by drazvan** [comment]
Hi @johnyoonh! I'm not sure I understand the issue. If you run the generation only with a message that contains the context updates (as in the first snippet you shared), then nothing happens because there's no user message to act on. In the RAG example notebook that you pointed to, the generation call includes both the context (with the relevant chunks) and the user query. 

Can you provide an example to reproduce the issue?
