### ISSUE TITLE
Azure GPT models not working

### ISSUE THREAD

**Issue by venkatesh3893** [NVIDIA/NeMo-Guardrails#590]
I am trying to establish guardrails setup for Azure OpenAI models. I have used the below configuration in config.yaml.  

models:
 -type: main
  engine: azure
  model: gpt-4
  parameters:
     azure_endpoint: ""
     api_version: "2023-07-01-preview"
     openai_api_version: "2023-07-01-preview"
     deployment_name: gpt-4
     api_key:""

I have tried multiple combinations and it just didnt work and no error was thrown.

**Comment by PeerBoerner1** [comment]
This is working for me right now on Azure.  I think you must ensure the model name you're using matches what's in your deployment details.  I'm using a different model below but the techniques should be the same. I hope this helps.

models:
  - type: main
    engine: azure
    model: gpt-4o
    parameters:
      azure_endpoint: https://yourendpoint.openai.azure.com/
      api_version: 2023-03-15-preview
      deployment_name: GPT-4o
      api_key: averylongsetofcharacters

**Comment by Pouyanpi** [comment]
Hi @venkatesh3893, could you follow @PeerBoerner1's solution?

**Comment by Pouyanpi** [comment]
@venkatesh3893 , since you've reacted with a thumbs up, I assume the issue has been resolved, and I proceed to close it.
