### ISSUE TITLE
How to get exception occurring within Nemoguardrails as output?

### ISSUE THREAD

**Issue by faisnain** [NVIDIA/NeMo-Guardrails#634]
I'm looking for a way to override system function like generate user Intent, input check. I tried add function with
@action(is_system=True)
async def generate_user_intent(......).....

still I don't see any print statements that I kept there is being executed. btw, I'm trying this cause I want to get the error that occurs while executing LLM calls. I want to handle each exception differently in my code.

**Comment by Pouyanpi** [comment]
Hi @faisnain, apologies for the delayed response. Could you please provide more details about your request? Exception handling has been generally improved in the most recent version, and the upcoming 0.10.0 release will include support for exception handling within Colang.
