### ISSUE TITLE
Colang 2.0 dict error

### ISSUE THREAD

**Issue by geraldhahn** [NVIDIA/NeMo-Guardrails#640]
Hi, I tried to use Colang 2.0 recently and implemented the simple tutorial script provided by NeMo guardrails.

The config.co file looks like this:

import core
import llm

flow main
    activate llm continuation
    activate greeting

flow greeting
    user expressed greeting
    bot express greeting

flow user expressed greeting
    user said 'hi' or user said 'hello'

flow bot express greeting
    bot say 'Hello World!'

When I run the code and input another greeting aside from 'hi'  or 'hello', just like 'hi there',
I get the following error message:

\nemoguardrails\colang\v2_x\runtime\serialization.py", line 107, in encode_to_dict
    raise Exception(f"Unhandled type in encode_to_dict: {type(obj)}")
Exception: Unhandled type in encode_to_dict: <class 'set'>

This seems to be an internal encoding error. Does anyone know how to fix this?

Thanks !

**Comment by Pouyanpi** [comment]
Hi @geraldhahn, thanks for opening this issue. 

The fix to this problem is already merged to the develop branch and will be available in 0.10.0 release. You can use the develop branch and install NeMo Guardrails from there.

**Comment by geraldhahn** [comment]
Thanks !

**Comment by Pouyanpi** [comment]
Hi @geraldhahn,

Please try v0.9.1 release which was published yesterday.
