### ISSUE TITLE
Disable .cache and .cache/embeddings folder creation

### ISSUE THREAD

**Issue by dan-ockham** [NVIDIA/NeMo-Guardrails#655]
I'm implementing guardrails in an azure function app and have a read-only file system where the application runs. 
I do not need to cache my embeddings but the .cache and /.cache/embeddings folder still get created.
This throws an error (trace below).
Is there any way to disable the creation of these folders?

`[Errno 30] Read-only file system: '.cache' Traceback (most recent call last): File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir os.mkdir(self, mode) FileNotFoundError: [Errno 2] No such file or directory: '.cache/embeddings' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/actions/action_dispatcher.py", line 197, in execute_action result = await result ^^^^^^^^^^^^ File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/actions/llm/generation.py", line 370, in generate_user_intent results = await self.user_message_index.search( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/embeddings/basic.py", line 268, in search _embedding = (await self._get_embeddings([text]))[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/embeddings/cache.py", line 305, in wrapper_decorator embeddings_cache = EmbeddingsCache.from_config(self.cache_config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/embeddings/cache.py", line 220, in from_config return cls.from_dict(config.to_dict()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/embeddings/cache.py", line 213, in from_dict cache_store = CacheStore.from_name(d.get("store"))(**store_config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/.python_packages/lib/site-packages/nemoguardrails/embeddings/cache.py", line 143, in __init__ self._cache_dir.mkdir(parents=True, exist_ok=True) File "/usr/local/lib/python3.11/pathlib.py", line 1120, in mkdir self.parent.mkdir(parents=True, exist_ok=True) File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir os.mkdir(self, mode) OSError: [Errno 30] Read-only file system: '.cache'`

**Comment by kaushikabhishek87** [comment]
I think it is disabled by default, check these docs:

https://github.com/NVIDIA/NeMo-Guardrails/blob/main/docs/user_guides/advanced/embedding-search-providers.md

Try explicitly defining these variables

**Comment by dan-ockham** [comment]
Even with enabled False explictly defined with a `store: filesystem` the .cache folder is created. To resolve I have changed store to `in_memory`.

**Comment by kaushikabhishek87** [comment]
cool, ideally I think it should not try to create cache when explicitly disabled

**Comment by Pouyanpi** [comment]
@dan-ockham, was your issue resolved after changing the cash store type to `in_memory` or you are still getting the error because of `.cache` directory which is created in `kb.py`? Thanks!
