### ISSUE TITLE
Fact check: Evidence is empty

### ISSUE THREAD

**Issue by alejandrods** [NVIDIA/NeMo-Guardrails#68]
Hello, 

I would like to use NEMO for check facts but I am having some problems to understand why the "relevant_chunks" is always empty in my case when I run the `check_facts`:

```python

COLANG_CONFIG = """
# Main Flow
define flow
    user ...
    $answer = execute qa_chain(query=$last_user_message)
    bot provide $answer
    $accurate = execute check_facts
    if not $accurate
        bot remove last message
        bot inform answer unknown

define bot remove last message
  "(remove last message)"
"""

def _get_qa_chain(llm, filters):
    """Initializes a QA chain using the jobs report.

    It uses OpenAI embeddings.
    """

    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=pinecone_langchain.as_retriever(search_kwargs={'filter': filters, "k": 8}),
    )

    return qa_chain


def demo():
    """Demo of using a chain as a custom action."""
    config = RailsConfig.from_content(COLANG_CONFIG, YAML_CONFIG)
    app = LLMRails(config, verbose=True)

    # Filters
    filters = ...

    # Create and register the chain directly as an action.
    qa_chain = _get_qa_chain(app.llm, filters)
    app.register_action(qa_chain, name="qa_chain")

    # mode = "chain"
    # mode = "chain_with_guardrails"
    mode = "chat_with_guardrails"

    if mode == "chain":
        user_message = input("> ")
        current_implementation_response = current_implementation(user_message, filters)
        result = qa_chain.run(user_message)
        print(result)

    elif mode == "chain_with_guardrails":
        user_message = input("> ")
        current_implementation_response = current_implementation(user_message, filters)
        history = [
            {"role": "user", "content": user_message}
        ]
        result = app.generate(messages=history)
        print(f"\033[92mWith NEMO---> {result['content']}\033[0m")

    elif mode == "chat_with_guardrails":
        history = []
        while True:
            user_message = input("> ")
            current_implementation_response = current_implementation(user_message, filters)

            history.append({"role": "user", "content": user_message})
            bot_message = app.generate(messages=history)
            history.append(bot_message)

            # We print bot messages in green.
            print(f"\033[92mWith NEMO---> {bot_message['content']}\033[0m")
            print("---------")
```

If I print the `context` received in the `check_facts()` function, I can see how the `relevant_chunks` is empty:

```
{'last_user_message': 'Is XXX better than XXX?', 'last_bot_message': 'It depends on what "better" means to you. Both XXX and XXX collect data from the same public data sources. XXX and XXX have different ...', 'answer': 'It depends on what "better" means to you. Both XXX and XXX collect data from the same public data sources.... 'relevant_chunks': ''}
```

Since the `relevant_chunks` is empty, `evidence` is empty so `check_facts` always returns `True`

**Comment by drazvan** [comment]
Hi @alejandrods!

Let me point you in the right direction. The reason that `relevant_chunks` is empty is because the knowledge base (i.e., the `/kb` folder) is empty. When using an "external" Q&A mechanism, like the `RetrievalQA` chain, you must manually set the `relevant_chunks` context variable before calling `check_facts`. To do that, you will have to set `return_source_documents` to `True` when initializing the chain and then adapt the colang logic to something like: 

```
define flow
    user ...

    # Because the `return_source_documents` is set, this will be a dict with an answer and source documents
    $response = execute qa_chain(query=$last_user_message)
    $answer = $response['answer']
    bot provide $answer

    $source_documents = $response['source_documents']
    $relevant_chunks = compute_relevant_chunks_from_source_docs(docs=$source_documents)

    $accurate = execute check_facts
    if not $accurate
        bot remove last message
        bot inform answer unknown
```

The `compute_relevant_chunks_from_source_docs` should be a custom action that is registered and takes the `List[Document]` structure from langchain and translate it into a string. 

I can't test right now, but if you can't get it to work, I can try to provide a complete example in the next couple of days.

**Comment by alejandrods** [comment]
@drazvan Thank you for your response. It works as expected:

```
define flow
    user ...
    # Because the `return_source_documents` is set, this will be a dict with an answer and source documents
    $response = execute qa_chain(query=$last_user_message)
    $answer = $response['result']
    bot provide $answer

    $source_documents = $response['source_documents']
    $relevant_chunks = execute compute_relevant_chunks_from_source_docs(docs=$source_documents)

    $accurate = execute check_facts
    if not $accurate
        bot remove last message
        bot inform answer unknown

define bot remove last message
  "(remove last message)"
```

**Comment by drazvan** [comment]
Great to hear that! If you have time and want to contribute an example that we can add to the examples folder, that would be great.

Thanks!

**Comment by jamontol** [comment]
Please @alejandrods  can you provide the implementation of "compute_relevant_chunks_from_source_docs" custom action. I've tried myself to do something like this:

```
@action()
async def compute_relevant_chunks(docs:list = None):

    list_of_docs = [source.page_content for source in docs['source_documents']]
    relevant_chunks = "\n".join(list_of_docs)
    
    return relevant_chunks 
```

but I get the following:

execute compute_relevant_chunks
# The result was None
bot inform internal error occurred
  "Action 'compute_relevant_chunks' not found."

**Comment by alejandrods** [comment]
@jamontol Mine is something like this:

```python
#actions.py
@action()
async def compute_relevant_chunks_from_source_docs(
    docs=None,
):
    sources = ""
    for doc in docs:
        sources += doc.page_content
    return sources
```

However, it looks like your problem is that it can't find the `compute_relevant_chunks` action. Make sure you have it in a script in the same folder as your `main` script. Something like this: 

```
- main.py
- actions.py
```

**Comment by jamontol** [comment]
> @jamontol Mine is something like this:
> 
> ```python
> #actions.py
> @action()
> async def compute_relevant_chunks_from_source_docs(
>     docs=None,
> ):
>     sources = ""
>     for doc in docs:
>         sources += doc.page_content
>     return sources
> ```
> 
> However, it looks like your problem is that it can't find the `compute_relevant_chunks` action. Make sure you have it in a script in the same folder as your `main` script. Something like this:
> 
> ```
> - main.py
> - actions.py
> ```

Thank you @alejandrods. 

The problem was indeed the wrong folder path in Rails Config. Now it works, but although the response is into the relevant chunks provided, check_facts returns False
