### ISSUE TITLE
Update Langchain version

### ISSUE THREAD

**Issue by sumeetag** [NVIDIA/NeMo-Guardrails#73]
Looks like NeMo-guard rails still require langchain version 0.0.167. 
Currently langchain 0.0.232 is active. 

Can the langchain version requirements be updated?

**Comment by drazvan** [comment]
Yes, we'll update. I've just tested and there doesn't seem to be any breaking changes. In an earlier version, ~0.0.200 there was something breaking, which probably got fixed, that's why we did not update.

**Comment by zhangjunqiang** [comment]
> Yes, we'll update. I've just tested and there doesn't seem to be any breaking changes. In an earlier version, ~0.0.200 there was something breaking, which probably got fixed, that's why we did not update.
Hello, i wanna know when will update the version?

**Comment by sumeetag** [comment]
Hi @drazvan, 
Any update on when can the langchain version be updated?

**Comment by drazvan** [comment]
I've just updated to 0.0.239. At the end of the month we'll publish 0.4.0 to PyPI.

**Comment by zhangjunqiang** [comment]
langchain 0.0.239 has some bugs. like:https://github.com/langchain-ai/langchain/pull/8064
it fixed at 0.0.240
bugs still at version from 0.0.236 to 0.0.239.
