### ISSUE TITLE
Trouble with guardrail output only

### ISSUE THREAD

**Issue by nhantran0506** [NVIDIA/NeMo-Guardrails#730]
Hi, I am working with guardrail output only but got the issues that it can go to the flow but return nothing.

Here is my config code 

```
rails:
  input:
    flows:
      - main

  output:
    flows:
      - outputnha
```

and here is my colang file 

```
define bot inform something
    "hehe"

define flow outputnha
    bot inform something
```

here is the main.py

```

config = RailsConfig.from_path("ollama_config")
app = LLMRails(config)



histtory = [{
    "role": "context",
    "content": {
        "history_context" : "my name is Nhan hehe"
    }
}, {
    "role": "assistant",
    "content": "My name is Nhan"
}]
res = app.generate(messages=histtory, 
    options={
    "rails": ["output"],
    "output_vars":True,
    "log": {
        "activated_rails": True,
        "llm_calls": True,
        "internal_events": True
    }
}
)
```

and the result it output 

```
response=[{'role': 'assistant', 'content': ''}] llm_output=None output_data={'last_user_message': None, 'last_bot_message': None, 'generation_options': {'rails': {'input': False, 'output': True, 'retrieval': False, 'dialog': False}, 'llm_params': None, 'llm_output': False, 'output_vars': True, 'log': {'activated_rails': True, 'llm_calls': True, 'internal_events': True, 'colang_history': False}}, 'bot_message': 'My name is Nhan', 'history_context': 'my name is Nhan hehe', 'event': {'type': 'Listen', 'uid': '71a7b36c-c2cb-4351-9c83-e2bae8dbc47c', 'event_created_at': '2024-09-04T10:02:13.638942+00:00', 'source_uid': 'NeMoGuardrails'}} log=GenerationLog(activated_rails=[], stats=GenerationStats(input_rails_duration=None, dialog_rails_duration=None, generation_rails_duration=None, output_rails_duration=None, total_duration=0.0009970664978027344, llm_calls_duration=0, llm_calls_count=0, llm_calls_total_prompt_tokens=0, llm_calls_total_completion_tokens=0, llm_calls_total_tokens=0), llm_calls=[], internal_events=[{'type': 'Listen', 'uid': '71a7b36c-c2cb-4351-9c83-e2bae8dbc47c', 'event_created_at': '2024-09-04T10:02:13.638942+00:00', 'source_uid': 'NeMoGuardrails'}], colang_history=None) state=None
No LLM calls were made.
```

it suppose to output "hehe" but in this case, empty string outputted. I don't understand and have a hard time debug and can't figuring out

**Comment by drazvan** [comment]
@nhantran0506 : when using the output rails only, both the user message and the assistant message must be provided in the history (even if just an empty string). 
https://docs.nvidia.com/nemo/guardrails/user_guides/advanced/generation-options.html#output-rails-only

```
res = rails.generate(messages=[{
    "role": "user",
    "content": ""
}, {
    "role": "bot",
    "content": "Some bot output."
}], options={
    "rails": ["output"]
})
```

Does this fix the issue for you?

**Comment by nhantran0506** [comment]
> [@nhantran0506](https://github.com/nhantran0506) : when using the output rails only, both the user message and the assistant message must be provided in the history (even if just an empty string). https://docs.nvidia.com/nemo/guardrails/user_guides/advanced/generation-options.html#output-rails-only
> 
> ```
> res = rails.generate(messages=[{
>     "role": "user",
>     "content": ""
> }, {
>     "role": "bot",
>     "content": "Some bot output."
> }], options={
>     "rails": ["output"]
> })
> ```
> 
> Does this fix the issue for you?

Thank you, I have another question, when the return of an action is False or string ( not empty ), the guardrail got it into a loop

```
if "yes" in response.lower():
            return False
        return bot_response
``

and my flow 

```
define flow outputnha
    $respond = execute CheckOutputAction
    if not $respond:
        bot refuse to respond
        stop    
    else:
        bot $bot_message
        stop
```


the error 

```
*Multiple time execute the CheckOutputAction then
Exception: Too many events.

```

is there any way to avoid this or what is the idea so I can got the output like mine idea ?

**Comment by cathleenyuan** [comment]
I am having the same too many events for my output only guardrail , 
 did you fix the Too many events issue ?
