### ISSUE TITLE
Dynamic loading trouble

### ISSUE THREAD

**Issue by nhantran0506** [NVIDIA/NeMo-Guardrails#734]
Hi, I wonder how can we load the config in dynamic way. In my case, the colang file and actions.py file stay the same among model, but I can't find a way to load different model as the main model

**Comment by Pouyanpi** [comment]
Hi @nhantran0506, apologies for the delay. Just to clarify, have you tried passing the llm while instantiating the LLMRails class? You can also use its 'update_llm' method.

**Comment by nhantran0506** [comment]
> Hi [@nhantran0506](https://github.com/nhantran0506), apologies for the delay. Just to clarify, have you tried passing the llm while instantiating the LLMRails class? You can also use its 'update_llm' method.

I don't know we can do that, I try to find the document for this but can't be found, could you send me the document linl please ?
