### ISSUE TITLE
Can not find a way to load actions file

### ISSUE THREAD

**Issue by leizory** [NVIDIA/NeMo-Guardrails#738]
Is there any way I can specific what action file to be loaded into guardrail ?

**Comment by DixitAdh** [comment]
@leizory  have you looked into custom_data config. You can either pass it in your config.yml or you can assign a value during instantiation of RunnableRails. You can retrieve the value of custom_data from railsconfig instance. I did something like this

``` python
config = RailsConfig.from_path(nemo_config_path)
custom_data = dict(blocked_terms_path=blocked_term_path)
config.custom_data = custom_data
guardrails = RunnableRails(config)
```

Used this custom_data in config.py 

``` python
  def _get_block_terms(config: RailsConfig):
    df = None
    xlsx_path = config.custom_data.get("blocked_terms_path")
    global blocked_terms_list
    try:
        df = pd.read_excel(xlsx_path)
    except FileNotFoundError:
        print("file {} does not exist".format(xlsx_path))
    blocked_terms_list = [x for x in set(df.to_numpy().flatten().tolist()) if str(x) != 'nan']
```

**Comment by Pouyanpi** [comment]
Hi @leizory 

Have you consulted this [link](https://docs.nvidia.com/nemo/guardrails/user_guides/configuration-guide.html?highlight=action)?

Besides defining actions in `actions.py` or `actions` subpackage as explained in the above link. You can use following method of LLMRails
```python
  register_action(action: callable, name: Optional[str] = None):
```

Have a look at [this example](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/examples/configs/rag/custom_rag_output_rails/config.py).

Please let me know if any of these helps or explain a bit more what you want to achieve.

**Comment by leizory** [comment]
> Hi [@leizory](https://github.com/leizory)
> 
> Have you consulted this [link](https://docs.nvidia.com/nemo/guardrails/user_guides/configuration-guide.html?highlight=action)?
> 
> Besides defining actions in `actions.py` or `actions` subpackage as explained in the above link. You can use following method of LLMRails
> 
>   register_action(action: callable, name: Optional[str] = None):
> Have a look at [this example](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/examples/configs/rag/custom_rag_output_rails/config.py).
> 
> Please let me know if any of these helps or explain a bit more what you want to
