### ISSUE TITLE
Multiple calls to LLM

### ISSUE THREAD

**Issue by sekhar-tcs** [NVIDIA/NeMo-Guardrails#743]
Hello, below is my config.yml file

rails:
  input:
    flows:
      - self check input
      - mask sensitive data on input
      - jailbreak detection heuristics
  config:
    sensitive_data_detection:
      input:
        entities:
          - PERSON
          - EMAIL_ADDRESS
          - ...  
    jailbreak_detection:
      server_endpoint: "http://0.0.0.0:1337/heuristics"
      length_per_perplexity_threshold: 89.79
      prefix_suffix_perplexity_threshold: 1845.65   
  output:
    flows:
      - self check output  
      - self check facts 
      - check hallucination

When I call the nemo guardrails with this configuration its making 3 calls to LLM. Is there any way we can restrict it to single call to the LLM for all my above checks.

**Comment by vmeharia** [comment]
Hi,

I am having similar issue, can you suggest how to restrict just 1 LLM call.

**Comment by Pouyanpi** [comment]
Hi @sekhar-tcs, you must note that in NeMo Guardrails "the interaction with the LLM is designed in a task-oriented way, i.e., each time the LLM is called, it must perform a specific task." So depending on the input and the tasks you have defined various LLM calls are made.

To better understand the LLM calls made and their usage, follow this [guide](https://docs.nvidia.com/nemo/guardrails/user_guides/advanced/generation-options.html#detailed-logging-information).

You can disable certain rails as explained [here](https://docs.nvidia.com/nemo/guardrails/user_guides/advanced/generation-options.html#disabling-rails). 

For dialog rails where **three LLM** calls are made you can use single call mode, please refer to this [doc](https://docs.nvidia.com/nemo/guardrails/user_guides/configuration-guide.html#single-call-mode).

You can also use embeddings only option to use the predefined messages within user and bot flows as discussed [here](https://docs.nvidia.com/nemo/guardrails/user_guides/configuration-guide.html#embeddings-only).

I hope following these guides would help you with this issue. Let me know if you need further assistance.
