### ISSUE TITLE
How can I pass in class in context.

### ISSUE THREAD

**Issue by nhantran0506** [NVIDIA/NeMo-Guardrails#746]
I wonder how can I pass in classes for variable in context just like below. I can not find any example about this, only see text and number

```
[{"role": "context", "content": {
        "index_store" : IndexClass,
        "retrieval_config" : retrieval_config,
        "retriver" : RetriverClass,
      }}]
```

**Comment by Pouyanpi** [comment]
It only works if the values provided are JSON Serializable as its corresponding event will be stored to a dictionary for caching. And Could you please elaborate on why you need this feature?

**Comment by nhantran0506** [comment]
> It only works if the values provided are JSON Serializable as its corresponding event will be stored to a dictionary for caching. And Could you please elaborate on why you need this feature?

Well, it is easier if I can execute a class method from outside and not set up that class all again in the action.
