### ISSUE TITLE
How to get bot message in self_check_output

### ISSUE THREAD

**Issue by QuyAnh2005** [NVIDIA/NeMo-Guardrails#757]
Hi, I am using `self_check_output` for my code. However, I also want to remain the original message and the output from `guardrails` as warning. How to do that?

**Comment by Pouyanpi** [comment]
Hi @QuyAnh2005, 

the easiest would be to update the `bot refuse to respond` canonical form. You can always access user message by (`$user_message`) and the bot response by (`$bot_message`). So add following to your .co file:

```
define bot refuse to respond 
  "I'm sorry, I can't respond to that. Blocked `$user_message` input. "
 ```

and you must note that bot self_check_input and output uses `refuse to respond` so maybe something like following would be helpful:

```
define bot refuse to respond 
  "I'm sorry, I can't respond to that. {% if user_message %}Blocked user message: '{{ user_message }}'.{% endif %}{% if bot_message %} Blocked bot message: '{{ bot_message }}'.{% endif %}"

```
So the above works for both self_check_input and output. Again note that there could be other flows using `bot refuse to respond` so you might need to adapt it.

I hope it helps!

**Comment by QuyAnh2005** [comment]
Thank you @Pouyanpi . I also find a similiar way

```
define flow self check output
  $allowed = execute self_check_output
  bot recall respond

  if not $allowed
    bot refuse to respond
    stop

define bot recall respond
  "{{ bot_message }}"
  
define bot refuse to respond
  "**There seems to be an anomaly here. Please check further.**"
```

**Comment by Pouyanpi** [comment]
Great, If you can use the `develop` branch, it might be also of interest to you to try out the [RaisException](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md#guardrails-library-exception) and look at some examples in the [library](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/self_check/) look at the flows.v1.co files.
