### ISSUE TITLE
Support for langchain 0.3.0

### ISSUE THREAD

**Issue by CatarinaG-skillup** [NVIDIA/NeMo-Guardrails#767]
Hi, do you have in your plans to update the code to make it compatible with the newest langchain versions?

Thanks a lot!

**Comment by Pouyanpi** [comment]
Hi @CatarinaG-skillup, we'll have it in the pipeline and would make it available as a patch release or in the the next one.

**Comment by ishaan-mehta** [comment]
Thanks! This would be great as there are a number of security vulnerabilities patched in the newer versions of LangChain (e.g., https://github.com/langchain-ai/langchain/commit/77209f315efd13442ec51c67719ba37dfaa44511)

**Comment by Pouyanpi** [comment]
Hi @CatarinaG-skillup, if you'd like to help with this upgrade, you can pull the draft PR and test it yourself. If you found any issue please add a comment to the PR. It really helps! Thanks
