### ISSUE TITLE
Umable to connect to Multimodal GPT models

### ISSUE THREAD

**Issue by venkatesh3893** [NVIDIA/NeMo-Guardrails#774]
I am not able to implement guardrails on Azure GPT-4 Turbo Vision models. Can you please share of any options available to implement guardrails on images

**Comment by Pouyanpi** [comment]
Hi @venkatesh3893, currently NeMo Guardrails does not support this. And there is not any plan to support it soon.

**Comment by ngk6311** [comment]
Is there still no support now?
