### ISSUE TITLE
Third party API (Cleanlab) integration undiscoverable in documentation

### ISSUE THREAD

**Issue by AshishSardana** [NVIDIA/NeMo-Guardrails#794]
Team, 

Cleanlab team integrated `trustworthiness_score` as part of 3rd party API that helps identify hallucinations. 
It has been a month since the PR is merged to `develop` branch, followed by multiple NeMo-Guardrails pypi releases (now on 0.10.1) but I don't see the [documentation](https://docs.nvidia.com/nemo/guardrails/search.html?q=cleanlab&check_keywords=yes&area=default) resulting in any results for a search for "Cleanlab".

Is there something I'm missing?

**Comment by Pouyanpi** [comment]
@AshishSardana unfortunately, the new version of the documentation is not published yet. So for the time being you need to use the docs on GitHub. Probably next week it will become available.

**Comment by AshishSardana** [comment]
@Pouyanpi I understand and will keep an eye on next week. Could you review (& approve) this quick PR that just changes return type from Cleanlab's method? https://github.com/NVIDIA/NeMo-Guardrails/pull/768

It'll help get this minor change in for next NeMo-Guardrails release, and for us to develop example notebooks off of it.
