### ISSUE TITLE
Bots don't reply to me in Japanese.

### ISSUE THREAD

**Issue by ydaigo** [NVIDIA/NeMo-Guardrails#8]
When I ask the bot a question in Japanese, it responds with "I'm sorry, I don't know the answer to that question.".

 I want to be able to converse with the bot in Japanese. 
What settings do I need to change to achieve this? 
I would like to report this issue on Github.

For example, I ask "先月の失業率を教えてください。". This mean "What was last month's unemployment rate?"
Bot response "I'm sorry, I don't know the answer to that question."
![image](https://user-images.githubusercontent.com/44220424/235194864-209dacb3-830f-4ed9-a339-a7a9a92670be.png)

**Comment by cparisien** [comment]
Thanks for your question. Unfortunately NeMo Guardrails is not yet multilingual. That's on our roadmap.

**Comment by ydaigo** [comment]
Thank you very much. I am looking forward to the multi-language support.
