### ISSUE TITLE
bug: nemoguardrails server does not properly stream responses when a single colang file is present in the config

### ISSUE THREAD

**Issue by serhatgktp** [NVIDIA/NeMo-Guardrails#850]
### Did you check docs and existing issues?

- [x] I have read all the NeMo-Guardrails docs
- [x] I have updated the package to the latest version before submitting this issue
- [x] (optional) I have used the develop branch
- [x] I have searched the existing issues of NeMo-Guardrails

### Python version (python --version)

Python 3.10.12

### Operating system/version

Ubuntu 22.04.1

### Describe the bug

nemoguardrails server is not properly returning streamed responses. While the Python API and CLI application seem to successfully stream responses, the same is not apparent over HTTP requests to nemoguardrails server.

Here is the file structure of my config directory:
```
config/
├─ streaming_policy/
│  ├─ config.yml
│  ├─ policy.co
```

Here is the my config.yml:
```
models:
  - type: main
    engine: openai
    model: gpt-4o

streaming: True
```

Here is my policy.co file:
```
define user ask about financial reports
  "Could you give me some information about the latest financial reports?"
  "What were the performance figures like last quarter?"

define user ask about developer code
  "Give me a list of our codebases."
  "How do you implement a binary tree in Python?"
  "Has the CI job on our deployment repository completed?"
```

Here is the code snippet that I am using to test streaming:
```py
import requests

def stream_chat_completion():
    url = "http://localhost:8000/v1/chat/completions"

    payload = {
        "model": {
            "id": "streaming_policy",
            "name": "streaming_policy",
            "maxLength": 10000,
            "tokenLimit": 10000
        },

        "messages": [
            {
                "role": "user",
                "content": "How does the internet work?"
            }
        ],

        "key": "",
        "prompt": "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.",
        "config_id": "streaming_policy",
        "stream": True
    }

    try:
        with requests.post(url, json=payload, stream=True) as response:
            response.raise_for_status() # Raise an exception for HTTP errors

            for chunk in response.iter_content(chunk_size=1024):
                if chunk:
                    print(chunk.decode("utf-8"), end=" ", flush=True)

    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    stream_chat_completion()
```

### Steps To Reproduce

1. Run the server via `nemoguardrails server`
2. Run the Python script included in the issue description

### Expected Behavior

The LLM output should be printed chunk-by-chunk as it is streamed from the server

### Actual Behavior

The output is printed all at once, after the LLM has finished generating entirely.

**Comment by Pouyanpi** [comment]
Hi @serhatgktp 

I followed the steps you provided to reproduce and assuming you are using head of develop branch, It works on my end. Given your implementation currently you are doing iter_lines, what if you change to:

```python
def stream_chat_completion():
    url = "http://localhost:8000/v1/chat/completions"

    payload = {
        "model": {
            "id": "streaming_policy",
            "name": "streaming_policy",
            "maxLength": 10000,
            "tokenLimit": 10000,
        },
        "messages": [{"role": "user", "content": "How does the internet work?"}],
        "key": "",
        "prompt": "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.",
        "config_id": "streaming_policy",
        "stream": True,
    }

    try:
        with requests.post(url, json=payload, stream=True) as response:
            # Raise an exception for HTTP errors
            response.raise_for_status()

            for chunk in response.iter_content(chunk_size=1024):
                if chunk:
                    print(chunk.decode("utf-8"), end=" ", flush=True)

    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
```
This change should make it more evident that the streaming is actually happening.

**Comment by serhatgktp** [comment]
Hi @Pouyanpi, thank you for your timely response. That's right, I am using the head of the `develop` branch. I tried this on a fresh installation after cloning the repo with `pip install -e .` in a fresh virtual environment.

Even with the modified test you've shared I still see on my end that the entire output of the LLM is printed into my terminal at the same time, rather than the response being streamed gradually. The difference is evident when I try streaming from OpenAI API directly, such as with the following script:

```py
import os
import requests
import json

def stream_chat_completion():
    # Retrieve the API key from environment variables
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY environment variable is not set.")

    # Define the API endpoint
    url = "https://api.openai.com/v1/chat/completions"

    # Set up the headers, including the Authorization header
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    # Define the payload as per the curl request
    payload = {
        "model": "gpt-4o",  # Ensure this is the correct model name
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "How does the internet work?"
            }
        ],
        "stream": True
    }

    try:
        # Send the POST request with streaming enabled
        with requests.post(url, headers=headers, json=payload, stream=True) as response:
            # Raise an exception for HTTP errors
            response.raise_for_status()

            # Iterate over the streamed response line by line
            for line in response.iter_lines():
                if line:
                    # Decode the line from bytes to string
                    decoded_line = line.decode('utf-8')
                    
                    # The streamed data is prefixed with "data: "
                    if decoded_line.startswith("data: "):
                        json_data = decoded_line[len("data: "):]
                        
                        if json_data == "[DONE]":
                            print("Stream finished.")
                            break
                        
                        # Parse the JSON data
                        try:
                            data = json.loads(json_data)
                            if 'choices' in data:
                                for choice in data['choices']:
                                    if 'delta' in choice and 'content' in choice['delta']:
                                        print(choice['delta']['content'], end='', flush=True)
                        except json.JSONDecodeError:
                            print("Received a non-JSON message:", json_data)
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    stream_chat_completion()
```

**Comment by serhatgktp** [comment]
Hi @Pouyanpi, I've updated the issue description by adding a single colang file `policy.co`. It is a simple colang file with generic flows, and no special actions or other functions. I have included its contents in the description.

It seems having a single colang file is enough to prevent the server from streaming properly. Could you see whether you're able to reproduce the issue with the addition of the single colang file? Thanks!

Note: I can also confirm that streaming seems to work properly when I remove the colang file and only keep the `config.yml` file in the config. I mistakenly claimed that my config consisted only of a single `config.yml` file whereas there were two extra files: a `.co` and a `.py` file. I was using the wrong config 😅 

cc: @cparisien

**Comment by Pouyanpi** [comment]
Also give `chat` cli a try:

```sh
nemoguardrails chat --config="path/to/config" --streaming"

```

Do you see the response being streamed?

**Comment by Pouyanpi** [comment]
Thank you @serhatgktp for catching this. The issue is with `StreamingHandler` and the predefined prefix, and suffix. 

these models use `openai-chatgpt.yml` prompts and for the `bot_message` output parser the predefined prefix and suffix in `llm.generation` blocks the streaming.

I'm going to open a PR that resolves this bug.
