### ISSUE TITLE
doc: Activefence moderation detailed doc outdated

### ISSUE THREAD

**Issue by noamlevy81** [NVIDIA/NeMo-Guardrails#892]
### Please also confirm the following

- [x] I have searched the [main issue tracker](https://github.com/NVIDIA/NeMo-Guardrails/issues) of NeMo Guardrails repository and believe that this is not a duplicate

### Issue Kind

Improving documentation

### Existing Link

https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user-guides/community/active-fence.md?plain=1#L34

### Description

The [action](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/activefence/actions.py#L29) does not expect text argument, so defining the suggested flow would break.

**Comment by noamlevy81** [comment]
Fix suggestion: https://github.com/NVIDIA/NeMo-Guardrails/pull/890

**Comment by cparisien** [comment]
Thanks @noamlevy81 for the doc fix! I merged your PR, closing the issue now.
