### ISSUE TITLE
Method `RailsConfig.from_path` only reads from the directory but the docstring implies it can read from `.co` file also

### ISSUE THREAD

**Issue by shabie** [NVIDIA/NeMo-Guardrails#94]
The doc string suggests the following:

https://github.com/NVIDIA/NeMo-Guardrails/blob/12c49bb99ee327f21fa8a7e31f97cef505b6fff1/nemoguardrails/rails/llm/config.py#L236

But in the actual code, this path is validated for being a directory or being a yaml. A direct path to a config file is not handled:

https://github.com/NVIDIA/NeMo-Guardrails/blob/12c49bb99ee327f21fa8a7e31f97cef505b6fff1/nemoguardrails/rails/llm/config.py#L248-L253

In fact, even in the README.md example, the it looks like we need to pass the path to the file (which is what I did) but it doesn't work:

https://github.com/NVIDIA/NeMo-Guardrails/blob/12c49bb99ee327f21fa8a7e31f97cef505b6fff1/README.md?plain=1#L99

I can make a PR to fix the documentation or a PR that also handles a direct path to the config file. I just need to know what is the preferred way.

The third options is I misunderstood that the config file should be YAML.

**Comment by drazvan** [comment]
Hi @shabie ! We should only support a folder. So I guess we need to update the documentation to make that clear. Thanks for the offer to contribute!

**Comment by shabie** [comment]
I'll make a PR with the suggested changes to documentation.
